export enum cotEntity {
    "Air Air Track",
    "Air Civ",
    "Air Civ fixed",
    "Air Civ fixed RPV, drone, UAV",
    "Air Civ rotary",
    "Air Civ Blimp",
    "Air Mil",
    "Air Mil Fixed",
    "Air Mil Fixed Gunship",
    "Air Mil Fixed Attack Strike",
    "Air Mil Fixed Bomber",
    "Air Mil Fixed Transport",
    "Air Mil Fixed Transport Heavy",
    "Air Mil Fixed Transport Light",
    "Air Mil Fixed Transport Medium",
    "Air Mil Fixed C2",
    "Air Mil Fixed Fighter",
    "Air Mil Fixed Interceptor",
    "Air Mil Fixed CSAR",
    "Air Mil Fixed ECM Jammer",
    "Air Mil Fixed Tanker",
    "Air Mil Fixed VSTOL",
    "Air Mil Fixed SOF",
    "Air Mil Fixed medevac",
    "Air Mil Fixed Patrol",
    "Air Mil Fixed Mine Countermeasures",
    "Air Mil Fixed ASUW",
    "Air Mil Fixed Drone,RPV,UAV",
    "Air Mil Fixed reconn",
    "Air Mil Fixed AEW",
    "Air Mil Fixed Photo",
    "Air Mil Fixed esm",
    "Air Mil Fixed ASW Carrier Based",
    "Air Mil Fixed Trainer",
    "Air Mil Fixed Utility",
    "Air Mil Fixed Utility Heavy",
    "Air Mil Fixed Utility Light",
    "Air Mil Fixed Utility Medium",
    "Air Mil Fixed C3I",
    "Air Mil Rotor",
    "Air Mil Rotor Transport",
    "Air Mil Rotor Transport Heavy",
    "Air Mil Rotor Transport Light",
    "Air Mil Rotor Transport Medium",
    "Air Mil Rotor C2",
    "Air Mil Rotor CSAR",
    "Air Mil Rotor Mine Countermeasures",
    "Air Mil Rotor ECM Jammer",
    "Air Mil Rotor Tanker",
    "Air Mil Rotor SOF",
    "Air Mil Rotor medevac",
    "Air Mil Rotor Drone,RPV,UAV",
    "Air Mil Rotor Reconnaissance",
    "Air Mil Rotor ASW MPA",
    "Air Mil Rotor Trainer",
    "Air Mil Rotor Utility",
    "Air Mil Rotor Utility Heavy)",
    "Air Mil Rotor Utility Light)",
    "Air Mil Rotor Utility Medium)",
    "Air Mil Blimp",
    "Air Weapon",
    "Air Weapon Decoy",
    "Air Weapon Missile In Flight",
    "Air Weapon Missile Air Launched",
    "Air Weapon Missile Air To Air",
    "Air Weapon Missile Air To Surface",
    "Air Weapon Missile Attack Missile",
    "Air Weapon Missile Land Launched Missile",
    "Air Weapon Missile SAM",
    "Air Weapon Missile SAM FixedSite",
    "Air Weapon Missile SAM Manpad",
    "Air Weapon Missile SAM Mobile",
    "Air Weapon Missile Surface To Surface (SSM)",
    "Air Weapon Missile Subsurface To Surface (S SSM)",
    "Ground",
    "Gnd Equipment",
    "Gnd Equip Sensor",
    "Gnd Equip Sensor Emplaced",
    "Gnd Equip Sensor Radar",
    "Gnd Equip Vehicle",
    "Gnd Equip Vehic Armor Gun",
    "Gnd Equip Vehic Armor APC",
    "Gnd Equip Vehic Armor APC Recovery",
    "Gnd Equip Vehic Armor C2V ACV",
    "Gnd Equip Vehic Armor Infantry",
    "Gnd Equip Vehic Armor Light",
    "Gnd Equip Vehic Armor Combat Service Support",
    "Gnd Equip Vehic Armor Tank",
    "Gnd Equip Vehic Armor Tank Heavy",
    "Gnd Equip Vehic Armor Tank Heavy Recovery",
    "Gnd Equip Vehic Armor Tank Light",
    "Gnd Equip Vehic Armor Tank Light Recovery",
    "Gnd Equip Vehic Armor Tank Medium",
    "Gnd Equip Vehic Civilian",
    "Gnd Equip Vehic Engineer",
    "Gnd Equip Vehic Mine Clearing Vehicle",
    "Gnd Equip Vehic Armored Mounted Mine Clearing Vehicle",
    "Gnd Equip Vehic Trailer Mounted Mine Clearing Vehicle",
    "Gnd Equip Vehic Bridge",
    "Gnd Equip Vehic Construction",
    "Gnd Equip Vehic Dozer",
    "Gnd Equip Vehic Earthmover",
    "Gnd Equip Vehic Mine Laying Vehicle",
    "Gnd Equip Vehic Bus",
    "Gnd Equip Vehic Limited Cross Country Truck",
    "Gnd Equip Vehic Boat",
    "Gnd Equip Vehic Boat Large",
    "Gnd Equip Vehic Boat Med",
    "Gnd Equip Vehic Boat Small",
    "Gnd Equip Vehic Semi",
    "Gnd Equip Vehic Cross Country Truck",
    "Gnd Equip Vehic Ambulance",
    "Gnd Equip Weapon",
    "Gnd Equip Weapon Air Defense Gun",
    "Gnd Equip Weapon DirectFire ",
    "Gnd Equip Weapon DirectFire Heavy Self Propelled",
    "Gnd Equip Weapon DirectFire Light",
    "Gnd Equip Weapon DirectFire Light Self Propelled",
    "Gnd Equip Weapon DirectFire Medium",
    "Gnd Equip Weapon DirectFire Medium Self Propelled",
    "Gnd Equip Weapon AntiTankGun",
    "Gnd Equip Weapon Atg Light",
    "Gnd Equip Weapon Atg Medium",
    "Gnd Equip Weapon Atg Recoilless",
    "Gnd Equip Weapon Howitzer",
    "Gnd Equip Weapon MissileLauncher",
    "Gnd Equip Weapon Mortar",
    "Gnd Equip Weapon Rifle Automatic Weapon",
    "Gnd Equip Weapon Rifle Rifle",
    "Gnd Equip Weapon RocketLauncher Single ",
    "Gnd Equip Weapon RocketLauncher AntiTank",
    "Gnd Equip Weapon Grenade Launcher",
    "Gnd Equip Special Equipment",
    "Gnd Equip Flame Thrower",
    "Gnd Equip Laser",
    "Gnd Equip Land Mines",
    "Gnd Equip Claymore",
    "Gnd Equip Less Than Lethal",
    "Gnd Equip NBC Equipment",
    "Gnd Building",
    "Gnd Structure Base Military",
    "Gnd Structure Base Airbase",
    "Gnd Structure Base Naval Base",
    "Gnd Structure Civilian",
    "Gnd Structure Civilian Bridge",
    "Gnd Structure Civilian Fence or Wall or Barrier",
    "Gnd Structure Civilian Canal",
    "Gnd Structure Civilian Canal Lock",
    "Gnd Structure Civilian Farm",
    "Gnd Structure Civilian Monument",
    "Gnd Structure Civilian Offices",
    "Gnd Structure Civilian Residence or Apartment or Hotel",
    "Gnd Structure Civilian Retail",
    "Gnd Structure Civilian School",
    "Gnd Structure Civilian vip",
    "Gnd Structure Civilian Warehouse",
    "Gnd Structure Factory",
    "Gnd Structure Government",
    "Gnd Structure IM Facilities",
    "Gnd Structure IM Facilities Emergency Management",
    "Gnd Structure IM Facilities Emergency Management Emergency Operations Center",
    "Gnd Structure IM Facilities Emergency Management Incident Commander",
    "Gnd Structure IM Facilities Emergency Management Incident Communications Center",
    "Gnd Structure IM Facilities Emergency Management Incident Command Post",
    "Gnd Structure IM Facilities Emergency Management War Room",
    "Gnd Structure IM Facilities Fire and Hazmat",
    "Gnd Structure IM Facilities Fire and Hazmat Fire Department",
    "Gnd Structure IM Facilities Health and Medical",
    "Gnd Structure IM Facilities Health and Medical Medical Dispatch",
    "Gnd Structure IM Facilities Law Enforcement",
    "Gnd Structure IM Facilities Law Enforcement Police Checkpoint",
    "Gnd Structure IM Facilities Law Enforcement Highway Patrol",
    "Gnd Structure IM Facilities Law Enforcement Local Police",
    "Gnd Structure IM Facilities Law Enforcement No Trespassing Zone",
    "Gnd Structure IM Facilities Law Enforcement Sheriffs Department",
    "Gnd Structure IM Facilities Law Enforcement State Police",
    "Gnd Structure IM Facilities Emergency Medical Services",
    "Gnd Structure IM Facilities Other",
    "Gnd Structure IM Facilities Other Agency Dispatch",
    "Gnd Structure IM Facilities Other Agency Dispatch ems",
    "Gnd Structure IM Facilities Other Agency Dispatch Fire",
    "Gnd Structure IM Facilities Other Agency Dispatch Highway",
    "Gnd Structure IM Facilities Other Agency Dispatch Media",
    "Gnd Structure IM Facilities Other Agency Dispatch Police Local",
    "Gnd Structure IM Facilities Other Agency Dispatch Police Station",
    "Gnd Structure IM Facilities Other Agency Dispatch Tow",
    "Gnd Structure IM Facilities Other Agency Dispatch Transit",
    "Gnd Structure IM Facilities Other Border Control Checkpoint",
    "Gnd Structure IM Facilities Other dmz",
    "Gnd Structure IM Facilities Other Independent Service Provider",
    "Gnd Structure IM Facilities Other Mobile Center",
    "Gnd Structure IM Facilities Other Mobile Center Fire",
    "Gnd Structure IM Facilities Other Mobile Center Medical",
    "Gnd Structure IM Facilities Other Mobile Center Law Enforcement",
    "Gnd Structure IM Facilities Other Message Center",
    "Gnd Structure IM Facilities Other Mobilization Center",
    "Gnd Structure IM Facilities Other Mobilization Center ems",
    "Gnd Structure IM Facilities Other Mobilization Center Transit",
    "Gnd Structure IM Facilities Other Mobilization Center Fire",
    "Gnd Structure IM Facilities Other Mobilization Center Highway",
    "Gnd Structure IM Facilities Other Mobilization Center Media",
    "Gnd Structure IM Facilities Other Mobilization Center Police Local",
    "Gnd Structure IM Facilities Other Mobilization Center Police Station",
    "Gnd Structure IM Facilities Other Mobilization Center Tow",
    "Gnd Structure IM Facilities Other Public Safety",
    "Gnd Structure IM Facilities Other Reporting Locations",
    "Gnd Structure IM Facilities Other Staging Area",
    "Gnd Structure IM Facilities Other Staging Area ems",
    "Gnd Structure IM Facilities Other Staging Area Fire",
    "Gnd Structure IM Facilities Other Staging Area Highway",
    "Gnd Structure IM Facilities Other Staging Area Media",
    "Gnd Structure IM Facilities Other Staging Area Police Local",
    "Gnd Structure IM Facilities Other Staging Area Police Station",
    "Gnd Structure IM Facilities Other Staging Area Tow",
    "Gnd Structure IM Facilities Other Staging Area Transit",
    "Gnd Structure IM Facilities Other Security Checkpoint",
    "Gnd Structure IM Facilities Other Segment",
    "Gnd Structure IM Facilities Other Transportation",
    "Gnd Structure IM Facilities Other Transportation Transit Incident Management Center",
    "Gnd Structure IM Facilities Other Transportation Transit Management Center",
    "Gnd Structure IM Facilities Other Transportation Traffic Inc Service Patrol Dispatch",
    "Gnd Structure IM Facilities Other Transportation Traffic Management Center",
    "Gnd Structure IM Facilities Other Temp",
    "Gnd Structure IM Facilities Other Temp Fire",
    "Gnd Structure IM Facilities Other Temp Medical",
    "Gnd Structure IM Facilities Other Temp Law Enforcement",
    "Gnd Structure IM Facilities Public Works",
    "Gnd Structure Mil Military Materiel Facility",
    "Gnd Structure Mil Aircraft Production",
    "Gnd Structure Mil NBC Warfare Production",
    "Gnd Structure Mil Ammunition Production",
    "Gnd Structure Mil Nuclear Energy",
    "Gnd Structure Mil Atomic Energy Reactor",
    "Gnd Structure Mil Nuclear Material Production",
    "Gnd Structure Mil Nuclear Weapons Grade",
    "Gnd Structure Mil Nuclear Material Storage",
    "Gnd Structure Mil Armament Production",
    "Gnd Structure Mil Missile+Space System Production",
    "Gnd Structure Mil Engineering Equipment Production",
    "Gnd Structure Mil Bridge",
    "Gnd Structure Mil Bridge Large",
    "Gnd Structure Mil Bridge Med",
    "Gnd Structure Mil Bridge Small",
    "Gnd Structure Mil Canal",
    "Gnd Structure Mil Ship Construction",
    "Gnd Structure Mil Military Vehicle Production",
    "Gnd Structure Processing Facility",
    "Gnd Structure Decon",
    "Gnd Structure Raw Material Production Storage",
    "Gnd Structure Mine",
    "Gnd Structure NBC",
    "Gnd Structure Biological",
    "Gnd Structure Chemical",
    "Gnd Structure Nuclear",
    "Gnd Structure petroleum gas oil",
    "Gnd Structure petroleum gas oil Refinery",
    "Gnd Structure Transport Facility",
    "Gnd Structure Transport Facility Airport",
    "Gnd Structure Transport Facility Helibase",
    "Gnd Structure Transport Facility Helispot",
    "Gnd Structure Transport Facility Land Port",
    "Gnd Structure Transport Facility Parking Garage",
    "Gnd Structure Transport Facility Railroad",
    "Gnd Structure Transport Facility Seaport",
    "Gnd Structure Utility Service, Research, Utility Facility",
    "Gnd Structure Utility Electric Power",
    "Gnd Structure Utility Electric Power Coal Power Plant",
    "Gnd Structure Utility Electric Power Hydroelectric Power Plant",
    "Gnd Structure Utility Electric Power Other Power",
    "Gnd Structure Utility Electric Power Power Substation",
    "Gnd Structure Utility Dam",
    "Gnd Structure Utility Fossil Fuel",
    "Gnd Structure Utility Nuclear Plant",
    "Gnd Structure Utility Public Water Services",
    "Gnd Structure Utility Technological Research",
    "Gnd Structure Utility Telecommunications",
    "Gnd Structure Utility Telecommunications Communications",
    "Gnd Structure Utility Telecommunications Communications Antenna Farm",
    "Gnd Structure Utility Telecommunications Communications Satellite Communications",
    "Gnd Structure Utility Telecommunications Communications Tower",
    "Gnd Structure Utility Telecommunications Radio",
    "Gnd Structure Utility Telecommunications Radio Station",
    "Gnd Structure Utility Telecommunications Telephone",
    "Gnd Structure Utility Telecommunications Television",
    "Gnd Structure Utility Telecommunications Television Cable",
    "Gnd Structure Utility Telecommunications Television Station",
    "Gnd Structure Medical Facility",
    "Gnd Structure Hospital",
    "Gnd Structure Medical Facility Hospital Hospital Care Facility",
    "Gnd Structure Road",
    "Gnd Structure Road Highway",
    "Gnd Structure Road Improved",
    "Gnd Structure Road Rest Area",
    "Gnd Structure Road Unimproved",
    "Gnd Combat unit",
    "Gnd Combat armor",
    "Gnd Combat Armor anti armor",
    "Gnd Combat Armor armor, wheeled",
    "Gnd Combat Armor armor, wheeled amphibious recovery",
    "Gnd Combat Defense air defense",
    "Gnd Combat Defense targeting unit",
    "Gnd Combat Engineer engineer",
    "Gnd Combat Artillery (Fixed)",
    "Gnd Combat airborne",
    "Gnd Combat light",
    "Gnd Combat mountain",
    "Gnd Combat air assault",
    "Gnd Combat Infantry Troops (Open)",
    "Gnd Combat Infantry Airborne",
    "Gnd Combat Infantry Arctic",
    "Gnd Combat Infantry Fighting Vehicle",
    "Gnd Combat Infantry Air Assault",
    "Gnd Combat Infantry Mechanized",
    "Gnd Combat Infantry DugIn",
    "Gnd Combat Recon ",
    "Gnd information warfare unit",
    "Gnd law enforcement unit",
    "Gnd civilian law enforcement",
    "Gnd central intelligence division (CID)",
    "Gnd security police (air)",
    "Gnd military police",
    "Gnd counter intelligence",
    "Gnd joint intelligence center",
    "Gnd meteorological",
    "Gnd operations",
    "Gnd interrogation",
    "Gnd surveillance",
    "Gnd IM Resources",
    "Gnd IM Resources Animal Health",
    "Gnd Incident Management Team Animal Protection",
    "Gnd IM Resources Emergency Management",
    "Gnd Mobile Feeding Kitchen",
    "Gnd Public Assistance Coordinator",
    "Gnd Rapid Needs Assessment Team",
    "Gnd Shelter Management Team",
    "Gnd Volunteer Agency Liaison",
    "Gnd IM Resources Emergency Medical Services",
    "Gnd Ambulances (Ground)",
    "Gnd Ambulance Strike Team",
    "Gnd Ambulance Task Force",
    "Gnd Emergency Medical Task Force",
    "Gnd IM Resources Fire hazmat",
    "Gnd Area Command Team, Firefighting",
    "Gnd Brush Patrol",
    "Gnd Crew Transport",
    "Gnd Engine, Fire (Pumper)",
    "Gnd Fire Boat",
    "Gnd Fuel Tender",
    "Gnd Fire Truck",
    "Gnd Foam Tender",
    "Gnd Hand Crew",
    "Gnd Helicopters Firefighting",
    "Gnd Helitanker ",
    "Gnd Mobile Communications Unit",
    "Gnd USCG National Strike Force",
    "Gnd Portable Pump",
    "Gnd Strike Team, Engine (Fire)",
    "Gnd Water Tender, Firefighting (Tanker)",
    "Gnd IM Resources Health and Medical",
    "Gnd Disaster Medical Assistance Team - Basic",
    "Gnd NDMS Management Support Team",
    "Gnd IM Resources Law Enforcement",
    "Gnd Bomb Squad Explosives Team",
    "Gnd Crowd Control Team",
    "Gnd Public Safety Dive Team",
    "Gnd Aviation-Helicopters Patrol Surveillance",
    "Gnd Observation Aircraft",
    "Gnd SWAT Tactical Team",
    "Gnd IM Resources Public Works",
    "Gnd Air Curtain Burners (Above Ground)",
    "Gnd Air Conditioner Heater",
    "Gnd Air Curtain Burners (In Ground)",
    "Gnd All Terrain Cranes",
    "Gnd Backhoe Loader",
    "Gnd Chillers Air Handlers",
    "Gnd Crawler Cranes",
    "Gnd Disaster Assessment Team",
    "Gnd Debris Management Monitoring Team",
    "Gnd Debris Management Site Reduction Team",
    "Gnd Debris Management Team",
    "Gnd Disaster Recovery Team",
    "Gnd Dump Trailer",
    "Gnd Dump Truck Off Road",
    "Gnd Dump Truck On Road",
    "Gnd Electrical Power Restoration Team",
    "Gnd Engineering Services",
    "Gnd Flat Bed Trailer Truck",
    "Gnd Generators ",
    "Gnd Hydraulic Excavator (Large)",
    "Gnd Hydraulic Excavator (Medium)",
    "Gnd Hydraulic Truck Cranes",
    "Gnd Lattice Truck Cranes",
    "Gnd Tug Boat",
    "Gnd Track Dozer",
    "Gnd Tub Grinder",
    "Gnd Tractor Trailer",
    "Gnd Wheel Dozer",
    "Gnd Water Purification Team",
    "Gnd Water Truck",
    "Gnd IM Resources Search and Rescue",
    "Gnd Airborne Reconnaissance",
    "Gnd Air Search Team",
    "Gnd Canine SAR Team Avalanche Snow",
    "Gnd Radio Direction Finding Team",
    "Gnd Swiftwater Flood Search and Dive Rescue Team",
    "Gnd USAR Incident Support Team",
    "Gnd USAR Task Force",
    "Gnd Wilderness SAR Team",
    "Gnd IM Resources Other",
    "Surface sea surface track",
    "Surface combatant",
    "Surface amphibious warfare ship",
    "Surface hovercraft",
    "Surface line",
    "Surface battleship",
    "Surface cruiser",
    "Surface carrier",
    "Surface destroyer",
    "Surface frigate corvette",
    "Surface mine warfare vessel",
    "Surface MCM support",
    "Surface MCM drone",
    "Surface minehunter",
    "Surface minelayer",
    "Surface minesweeper",
    "Surface patrol",
    "Surface antisubmarine warfare",
    "Surface antisurface warfare",
    "Surface noncombatant",
    "Surface fishing",
    "Surface merchant",
    "Surface cargo",
    "Surface ferry",
    "Surface oiler tanker",
    "Surface passenger",
    "Surface tug",
    "Surface leisure craft",
    "SubSurf diver",
    "SubSurf submarine",
    "Other",
    "Other incident",
    "Other incident geo",
    "Other incident geo avalanche",
    "Other incident geo earthquake",
    "Other incident geo landslide",
    "Other incident geo subsistance",
    "Other incident geo volcano",
    "Other incident geo eruption",
    "Other incident met",
    "Other incident met drizzle",
    "Other incident met drought",
    "Other incident met flood",
    "Other incident met fog",
    "Other incident met hail",
    "Other incident met rain",
    "Other incident met sandstorm",
    "Other incident met snow",
    "Other incident metthunderstorm",
    "Other incident met tornado",
    "Other incident met cyclone",
    "Other incident met tsunami",
    "Other incident safety",
    "Other incident security",
    "Other incident security civil disturb",
    "Other incident security civil disturb demonstration",
    "Other incident security civil disturb displaced",
    "Other incident security civil disturb rioting",
    "Other incident security law enforcement",
    "Other incident security law enforcement bombing",
    "Other incident security law enforcement bomb explosion",
    "Other incident security law enforcementbomb threat",
    "Other incident security law enforcement looting",
    "Other incident security law enforcement poisoning",
    "Other incident security law enforcement shooting",
    "Other incident rescue",
    "Other incident fire",
    "Other incident fire wild",
    "Other incident fire non residential",
    "Other incident fire non residential special need",
    "Other incident fire non residential school",
    "Other incident fire residential",
    "Other incident fire hot spot",
    "Other incident fire origin",
    "Other incident fire smoke",
    "Other incident fire special needs",
    "Other incident medical public health",
    "Other incident pollution environmental",
    "Other incident transportation ",
    "Other incident transportation air",
    "Other incident transportation air accident",
    "Other incident transportation air hijacking",
    "Other incident transportation maritime",
    "Other incident transportation maritime accident",
    "Other incident transportation maritime hijacking",
    "Other incident transportation rail",
    "Other incident transportation rail accident",
    "Other incident transportation rail hijacking",
    "Other incident transportation vehicle",
    "Other incident transportation vehicle accident",
    "Other incident transportation vehicle hijacking",
    "Other incident infrastructure",
    "Other incident CBRNE",
    "Other incident other",
    "Space track",
    "Crewed space vehicle",
    "Satellite",
    "Space station",
    "SOF Unit",
    "Aviation",
    "Fixed wing",
    "Attack",
    "Ranger",
    "Special forces",
    "Naval",
    "SEAL",
    "Support",
    "Airborne command post",
    "Fighter",
    "Medevac",
    "Patrol",
    "Combat search &amp; rescue (CSAR)",
    "Special operations forces (SOF)",
    "Tanker",
    "Trainer",
    "Utility",
    "Bomb",
    "Ballistic missile",
    "Automobile",
    "Jeep type vehicle",
    "Multi-passenger vehicle",
    "Open-bed truck",
    "Tractor trailer truck with box trailer",
    "Tractor trailer truck with flatbed trailer",
    "Utility vehicle",
    "Armored assault",
    "Armored engineer recon vehicle (AERV)",
    "Backhoe",
    "Ferry transporter",
    "Crane loading device",
    "Ambulance",
    "Tow truck",
    "Medium",
    "Tank",
    "Antisubmarine warfare mission package",
    "Mine warfare mission package",
    "Surface warfare (SUW) mission package",
    "Anti-ship missile",
    "Gun",
    "Torpedo",
    "Electronic surveillance measures",
    "Photographic",
    "Compact",
    "Midsize",
    "Sedan",
    "Large heavy",
    "Small light",
    "Large bus",
    "Small bus",
    "Van",
    "Large open-bed truck",
    "Pickup truck",
    "Small open-bed truck",
    "Large heavy box trailer",
    "Medium box trailer",
    "Small light box trailer",
    "Large heavy flatbed trailer",
    "Medium flatbed trailer",
    "Small light flatbed trailer",
    "Large box truck",
    "Small box truck",
    "Sport utility vehicle (SUV)",
    "Armored dozer",
    "Armored utility vehicle",
    "Heavy semi",
    "Light semi",
    "Medium semi",
    "Heavy tow truck",
    "Light tow truck",
    "Chaparral",
    "C2",
    "Meteorological",
    "Int. range AD missile launcher TELAR",
    "Int. range AD missile launcher TLAR",
    "Long range AD missile launcher TELAR",
    "Long range AD missile launcher TLAR",
    "Short range AD missile launcher TELAR",
    "Short range AD missile launcher TLAR",
    "AD missile launcher theater TELAR",
    "AD missile launcher theater TLAR",
    "Mayday message",
    "sensor point",
    "observation point",
    "grid",
    "Alarm",
    "Alarm/CBRNE",
    "Alarm/CBRNE/BioChem",
    "Alarm/CBRNE/BioChem/Biological",
    "Alarm/CBRNE/BioChem/Chemical",
    "Alarm/CBRNE/Explosive",
    "Alarm/CBRNE/Explosive/Device",
    "Alarm/CBRNE/NuclearRadiological",
    "Alarm/CBRNE/NuclearRadiological/Nuclear",
    "Alarm/CBRNE/NuclearRadiological/Nuclear/Bomb",
    "Alarm/CBRNE/NuclearRadiological/Nuclear/Special Nuclear Material",
    "Alarm/CBRNE/NuclearRadiological/Radiological",
    "Alarm/CBRNE/Radiological/Dispersal Device (Dirty Bomb)",
    "Alarm/Environmental",
    "Alarm/Environmental/Hazmat",
    "Alarm/Fire",
    "Alarm/Fire/Audible",
    "Alarm/Fire/Audible/Pump Activated",
    "Alarm/Fire/Audible/Combustion",
    "Alarm/Fire/Audible/Duct Detector",
    "Alarm/Fire/Audible/Flame Detector",
    "Alarm/Fire/Audible/Heat",
    "Alarm/Fire/Audible/Pull Station",
    "Alarm/Fire/Audible/Smoke",
    "Alarm/Fire/Audible/Waterflow",
    "Alarm/Geophysical",
    "Alarm/Medical and Public Health",
    "Alarm/Medical and Public Health/Audible",
    "Alarm/Medical and Public Health/Ambulance",
    "Alarm/Medical and Public Health/Ambulance/Silent",
    "Alarm/Infrastructure",
    "Alarm/Security",
    "Alarm/Security/Law Enforcement",
    "Alarm/Security/Law Enforcement/Armed and Dangerous",
    "Alarm/Security/Law Enforcement/Animal",
    "Alarm/Security/Law Enforcement/Animal/On Roadway",
    "Alarm/Security/Law Enforcement/Assualt",
    "Alarm/Security/Law Enforcement/Abandoned Vehicle",
    "Alarm/Security/Law Enforcement/Battery",
    "Alarm/Security/Law Enforcement/Bomb Threat",
    "Alarm/Security/Law Enforcement/Burglary",
    "Alarm/Security/Law Enforcement/Burglary/Audible",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Day/Night Zone",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Entry/Exit",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Interior",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Outdoor",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Perimeter",
    "Alarm/Security/Law Enforcement/Burglary/Audible/24 Hour Zone",
    "Alarm/Security/Law Enforcement/Burglary/Audible/Exit Error",
    "Alarm/Security/Law Enforcement/Burglary/Silent",
    "Alarm/Security/Law Enforcement/Burglary/Silent/Recent Close",
    "Alarm/Security/Law Enforcement/Crash",
    "Alarm/Security/Law Enforcement/Crash/Aircraft",
    "Alarm/Security/Law Enforcement/Crash/With Fatalities",
    "Alarm/Security/Law Enforcement/Crash/With injuries",
    "Alarm/Security/Law Enforcement/Crash/With Roadblock",
    "Alarm/Security/Law Enforcement/Crash/Patrol Car",
    "Alarm/Security/Law Enforcement/Child Abuse",
    "Alarm/Security/Law Enforcement/Civil Disturbance or Disorder",
    "Alarm/Security/Law Enforcement/Callbox Request",
    "Alarm/Security/Law Enforcement/Drug or Contraband",
    "Alarm/Security/Law Enforcement/Domestic Violence",
    "Alarm/Security/Law Enforcement/Dead Person",
    "Alarm/Security/Law Enforcement/Drunk Pedestrian",
    "Alarm/Security/Law Enforcement/DUI/Juvenile",
    "Alarm/Security/Law Enforcement/Disabled Vehicle",
    "Alarm/Security/Law Enforcement/Escaped Prisoner",
    "Alarm/Security/Law Enforcement/Hit and Run",
    "Alarm/Security/Law Enforcement/Hit and Run/With Injuries",
    "Alarm/Security/Law Enforcement/Hit and Run/With Roadblock",
    "Alarm/Security/Law Enforcement/Hold Up",
    "Alarm/Security/Law Enforcement/Hold Up/Audible",
    "Alarm/Security/Law Enforcement/Hold Up/Silent",
    "Alarm/Security/Law Enforcement/Information or Intelligence - calls to take witness info",
    "Alarm/Security/Law Enforcement/Impersonating an Officer",
    "Alarm/Security/Law Enforcement/Juvenile Offense",
    "Alarm/Security/Law Enforcement/Kidnapping",
    "Alarm/Security/Law Enforcement/Larceny",
    "Alarm/Security/Law Enforcement/Murder",
    "Alarm/Security/Law Enforcement/Mentally Ill Person",
    "Alarm/Security/Law Enforcement/Malacious Mischief",
    "Alarm/Security/Law Enforcement/Missing Person",
    "Alarm/Security/Law Enforcement/Officer Down",
    "Alarm/Security/Law Enforcement/Pedestrian or Hitchhiker",
    "Alarm/Security/Law Enforcement/Robbery",
    "Alarm/Security/Law Enforcement/Robbery/Strongarm",
    "Alarm/Security/Law Enforcement/Reckless Driving",
    "Alarm/Security/Law Enforcement/Rock Throwing",
    "Alarm/Security/Law Enforcement/Shooting",
    "Alarm/Security/Law Enforcement/Suspicious Circumstances",
    "Alarm/Security/Law Enforcement/Special Detail",
    "Alarm/Security/Law Enforcement/Smuggling",
    "Alarm/Security/Law Enforcement/Sick or Injured Person",
    "Alarm/Security/Law Enforcement/Sex Offense",
    "Alarm/Security/Law Enforcement/Suspicious Person",
    "Alarm/Security/Law Enforcement/Suicide",
    "Alarm/Security/Law Enforcement/Suspicious Vehcle",
    "Alarm/Security/Law Enforcement/Toll Evasion",
    "Alarm/Security/Law Enforcement/Lost or Stolen Vehicle Tag",
    "Alarm/Meteorological",
    "Alarm/Other",
    "Alarm/Other/Cancel",
    "Alarm/Other/Close",
    "Alarm/Other/Close/Silent",
    "Alarm/Other/Close/Silent/Stay Mode",
    "Alarm/Other/Forced Arming",
    "Alarm/Other/Forced Arming/Silent",
    "Alarm/Other/Forced Arming/Silent/Partial Arm",
    "Alarm/Other/Failure to Test",
    "Alarm/Other/Failure to Test/Silent",
    "Alarm/Other/Failure to Test/Silent/Point not Tested",
    "Alarm/Other/Log",
    "Alarm/Other/Panic",
    "Alarm/Other/Reset",
    "Alarm/Other/Reset/Silent",
    "Alarm/Other/Reset/Silent/Exp Mod Reset",
    "Alarm/Other/Special",
    "Alarm/Other/Special/Audible",
    "Alarm/Other/Special/Audible/General Alarm",
    "Alarm/Other/Special/Audible/Personal Emergency",
    "Alarm/Other/Special/Audible/Air Flow Loss",
    "Alarm/Other/Special/Audible/Gas Detected",
    "Alarm/Other/Special/Audible/Low Gas Level",
    "Alarm/Other/Special/Audible/Water Leakage",
    "Alarm/Other/Special/Silent",
    "Alarm/Other/Special/Silent/Fail to Report",
    "Alarm/Other/Special/Silent/Listen in to Follow",
    "Alarm/Other/Supress",
    "Alarm/Other/Supress/Audible",
    "Alarm/Other/Supress/Audible/Gate Valve Tamper",
    "Alarm/Other/Supress/Silent",
    "Alarm/Other/Supress/Silent/Alarm Relay Disabled",
    "Alarm/Other/Supress/Silent/Bell 1 Disabled",
    "Alarm/Other/Supress/Silent/Bell 2 Disabled",
    "Alarm/Other/Supress/Silent/Dialer Disabled",
    "Alarm/Other/Supress/Silent/Reversing Relay Disabled",
    "Alarm/Other/Supress/Silent/Radio Transmitter Disabled",
    "Alarm/Other/Supress/Silent/Sounder relay Disabled",
    "Alarm/Other/Supress/Silent/Trouble Relay Disabled",
    "Alarm/Other/Tamper",
    "Alarm/Other/Tamper/Audible",
    "Alarm/Other/Tamper/Silent",
    "Alarm/Other/Tamper/Silent/Expansion Module",
    "Alarm/Other/Tamper/Silent/Panel Program Change",
    "Alarm/Other/Tamper/Silent/Sensor",
    "Alarm/Other/Tamper/Silent/Verify",
    "Alarm/Other/Trouble",
    "Alarm/Other/Trouble/Audible",
    "Alarm/Other/Trouble/Audible/Foil Break",
    "Alarm/Other/Trouble/Audible/Low CO2",
    "Alarm/Other/Trouble/Audible/Day Trouble",
    "Alarm/Other/Trouble/Audible/Exit error",
    "Alarm/Other/Trouble/Audible/Low Water Level",
    "Alarm/Other/Trouble/Audible/Low  Water Pressure",
    "Alarm/Other/Trouble/Audible/Pump Failure",
    "Alarm/Other/Trouble/Silent",
    "Alarm/Other/Trouble/Silent/Sensor",
    "Alarm/Other/Trouble/Silent/Alarm Relay",
    "Alarm/Other/Trouble/Silent/Low System Battery",
    "Alarm/Other/Trouble/Silent/Bell 1",
    "Alarm/Other/Trouble/Silent/Bell 2",
    "Alarm/Other/Trouble/Silent/Battery Test Fail",
    "Alarm/Other/Trouble/Silent/Polling Loop Close",
    "Alarm/Other/Trouble/Silent/Communication Fail",
    "Alarm/Other/Trouble/Silent/Exp Mod DC Loss",
    "Alarm/Other/Trouble/Silent/Detector Hi Sens",
    "Alarm/Other/Trouble/Silent/Detector Low Sens",
    "Alarm/Other/Trouble/Silent/Expansion Mod Fail",
    "Alarm/Other/Trouble/Silent/Event Log 50% Full",
    "Alarm/Other/Trouble/Silent/Event Log 90% Full",
    "Alarm/Other/Trouble/Silent/Expansion Module Fail",
    "Alarm/Other/Trouble/Silent/Event Log Overflow",
    "Alarm/Other/Trouble/Silent/Fire Trouble",
    "Alarm/Other/Trouble/Silent/Ground Fault",
    "Alarm/Other/Trouble/Silent/Exp Mod Low Battery",
    "Alarm/Other/Trouble/Silent/Protection Loop Open",
    "Alarm/Other/Trouble/Silent/Lost Polling",
    "Alarm/Other/Trouble/Silent/Long Range Radio",
    "Alarm/Other/Trouble/Silent/Protection Loop Short",
    "Alarm/Other/Trouble/Silent/RPM Supervision",
    "Alarm/Other/Trouble/Silent/Near Alarm",
    "Alarm/Other/Trouble/Silent/Polling Loop Open",
    "Alarm/Other/Trouble/Silent/AC Power Lost",
    "Alarm/Other/Trouble/Silent/Printer Failure",
    "Alarm/Other/Trouble/Silent/Protection Loop",
    "Alarm/Other/Trouble/Silent/Printer Paper Out",
    "Alarm/Other/Trouble/Silent/Polling Loop Short",
    "Alarm/Other/Trouble/Silent/Radio Antenna Vswr",
    "Alarm/Other/Trouble/Silent/Repeater Failure",
    "Alarm/Other/Trouble/Silent/RF Low Battery",
    "Alarm/Other/Trouble/Silent/Reversing Relay",
    "Alarm/Other/Trouble/Silent/RF Supervision",
    "Alarm/Other/Trouble/Silent/Smoke Det Hi Sens",
    "Alarm/Other/Trouble/Silent/Smoke Det Low Sens",
    "Alarm/Other/Trouble/Silent/System Peripheral",
    "Alarm/Other/Trouble/Silent/Sounder/Relay",
    "Alarm/Other/Trouble/Silent/System Shutdown",
    "Alarm/Other/Trouble/Silent/Self Test Failure",
    "Alarm/Other/Trouble/Silent/Telco Line 1",
    "Alarm/Other/Trouble/Silent/Telco Line 2",
    "Alarm/Other/Trouble/Silent/Time/Date Inaccurate",
    "Alarm/Other/Trouble/Silent/Trouble Relay",
    "Alarm/Other/Trouble/Silent/RAM Checksum Bad",
    "Alarm/Other/Trouble/Silent/ROM Checksum Bad",
    "Alarm/Other/Temperature",
    "Alarm/Other/Temperature/Audible",
    "Alarm/Other/Temperature/Audible/High Temperature",
    "Alarm/Other/Temperature/Audible/Low Temperature",
    "Alarm/Other/Temperature/Audible/Loss of Heat",
    "Alarm/Other/Temperature/Audible/Refrigeration",
    "Alarm/Other/Test",
    "Alarm/Other/Test/SIlent",
    "Alarm/Other/Test/SIlent/Fire Alarm",
    "Alarm/Other/Test/SIlent/Manual",
    "Alarm/Other/Test/SIlent/Point Tested OK",
    "Alarm/Other/Test/SIlent/System Remains in Trouble",
    "Alarm/Other/Test/SIlent/Walk Test Mode Entered",
    "Alarm/Rescue",
    "Alarm/Safety",
    "Alarm/Transportation",
    "Alarm/Transportation/Vehicle",
    "Alarm/Transportation/Vehicle/Accident",
    "Alarm/Transportation/Vehicle/Accident/Collision",
    "Alarm/Transportation/Vehicle/Accident/Collision/Fixed Object",
    "Alarm/Transportation/Vehicle/Accident/Collision/Non-Fixed Object",
    "Alarm/Transportation/Vehicle/Accident/Equipment/Cargo Loss/Shift",
    "Alarm/Transportation/Vehicle/Accident/Fire_Explosion",
    "Alarm/Transportation/Vehicle/Accident/Immersion",
    "Alarm/Transportation/Vehicle/Accident/Jacknife",
    "Alarm/Transportation/Vehicle/Accident/Object Thrown/Fallen",
    "Alarm/Transportation/Vehicle/Accident/Overturn_Rollover",
    "Alarm/Transportation/Vehicle/Accident/Person Fell or Jumped",
    "Alarm/Transportation/Vehicle/Other (Non Collision)",
    "SEAD",
    "Strike",
    "Destroy",
    "Investigate",
    "Target",
    "Mensurate",
    "Tasking Update",
    "Tasking Status Query",
    "Tasking Cancel",
    "Tasking (Experimental)",
    "Tasking Data Retrieval",
    "Link Dereference",
    "App control- Sync (with peer)",
    "App control- Sync (subscribe)",
    "Filter",
    "Open",
    "Medevac3",
    "Reply",
    "Ack",
    "Rcvd",
    "Wilco",
    "Tasking Complete",
    "Fail",
    "Fail= No Assets",
    "Fail= Bad Reqest (CANTPRO)",
    "Fail= Denied",
    "Fail= Insufficient Info",
    "Fail= Rejected",
    "Fail= C2 element",
    "Fail= Platform (CANTCO)",
    "Fail= Stale",
    "Fail= Cancelled",
    "Complete= Success",
    "Status= Status",
    "Status= Canceling",
    "Status= Executing",
    "Status= Approved",
    "Status= Disseminating",
    "Status= Disseminated",
    "Status= Imagery Available",
    "Status= MISREP available",
    "Status= Planning",
    "Status= Reviewing",
    "METOC",
    "ATMOSPHERIC",
    "Temperature",
    "PRESSURE SYSTEMS",
    "LOW PRESSURE CENTER",
    "HIGH PRESSURE CENTER",
    "FRONTAL SYSTEMS",
    "COLD FRONT",
    "UPPER COLD FRONT",
    "WARM FRONT",
    "UPPER WARM FRONT",
    "OCCLUDED FRONT",
    "STATIONARY FRONT",
    "LINES",
    "TROUGH LINE",
    "RIDGE LINE",
    "SQUALL LINE",
    "TURBULENCE",
    "LIGHT TURBULENCE",
    "MODERATE TURBULENCE",
    "SEVERE TURBULENCE",
    "EXTREME TURBULENCE",
    "ICING",
    "CLEAR ICING",
    "LIGHT CLEAR ICING",
    "MODERATE CLEAR ICING",
    "SEVERE CLEAR ICING",
    "RIME ICING",
    "LIGHT RIME ICING",
    "MODERATE RIME ICING",
    "SEVERE RIME ICING",
    "MIXED ICING",
    "LIGHT MIXED ICING",
    "MODERATE MIXED ICING",
    "SEVERE MIXED ICING",
    "WIND BARB",
    "JET STREAM",
    "FLIGHT RULES",
    "INSTRUMENT CEILING",
    "VISUAL CEILING",
    "COVERAGE SYMBOLS",
    "Cloud tops",
    "Cloud base",
    "Cloud ceiling",
    "Total Cloud Coverage",
    "CLEAR SKY (SKC)",
    "SCATTERED SKY (SCT)",
    "BROKEN SKY (BKN)",
    "OVERCAST WITH BREAKS",
    "OVERCAST (OVC)",
    "SKY OBSCURED OR PARTIALLY OBSCURED",
    "PRECIPITATION",
    "RAIN (RA)",
    "RAIN SHOWER",
    "FREEZING RAIN (FZRA)",
    "DRIZZLE (DZ)",
    "FREEZING DRIZZLE (FZDZ)",
    "SNOW(SN)",
    "SNOW SHOWERS",
    "SNOW GRAINS (SG)",
    "HAIL",
    "ICE PELLETS (PE)",
    "ICE CRYSTALS (IC)",
    "STORMS",
    "THUNDERSTORMS (TS)",
    "THUNDERSTORM (TS) WITH RAIN (RA) ",
    "FUNNEL CLOUD (FC)/TORNADO/WATERSPOUT",
    "LIGHTNING (LTG)",
    "STORM SYSTEMS",
    "TROPICAL STORM",
    "HURRICANE",
    "OBSTRUCTIONS TO VISIBILITY",
    "BLOWING SNOW (BLSN)",
    "FOG (FG)",
    "FREEZING FOG (FZFG)",
    "DUST/SAND STORM",
    "DUST DEVIL",
    "SMOKE (FU)",
    "HAZE (HZ)",
    "BLOWING DUST OR SAND",
    "OCEANIC",
    "SPACE",
    "HEALTH/CASUALTY",
    "MILITARY OPERATIONS OTHER THAN WAR (MOOTW)",
    "VIOLENT ACTIVITIES (DEATH CAUSING)",
    "ARSON/FIRE",
    "ASSASSINATION/MURDER/EXECUTION",
    "BOMB/BOMBING",
    "BOOBY TRAP",
    "DRIVE BY SHOOTING",
    "SNIPING",
    "POISONING",
    "LOCATIONS",
    "BLACK LIST LOCATION",
    "GRAY LIST LOCATION",
    "WHITE LIST LOCATION",
    "OPERATIONS",
    "PATROLLING",
    "RECRUITMENT",
    "RECRUITMENT (WILLING)",
    "RECRUITMENT (COERCED/IMPRESSED)",
    "DEMONSTRATION",
    "MINE LAYING",
    "PSYCHOLOGICAL OPERATIONS (PSYOP)",
    "PSYOP (TV AND RADIO PROPAGANDA)",
    "PSYOP (WRITTEN PROPAGANA)",
    "HOUSE TO HOUSE PROPAGANDA",
    "FORAGING/SEARCHING",
    "SPY",
    "FOOD DISTRIBUTION",
    "EXTORTION",
    "HIJACKING",
    "HIJACKING (VEHICLE)",
    "HIJACKING (AIRPLANE)",
    "HIJACKING (BOAT)",
    "KIDNAPPING",
    "ARREST",
    "DRUG OPERATION",
    "ITEMS",
    "REFUGEES",
    "SAFE HOUSE",
    "GRAFITTI",
    "VANDALISM/RAPE/LOOT/RANSACK/PLUNDER/SACK",
    "KNOWN INSURGENT VEHICLE",
    "DRUG VEHICLE",
    "INTERNAL SECURITY FORCE",
    "NON-COT OBJECT"
}
