import { cotEntity } from './cotEntityEnum'

// https://github.com/dB-SPL/cot-types/blob/main/CoTtypes.xml
// https://github.com/FreeTAKTeam/FreeTakServer/blob/master/FreeTAKServer/model/RestMessages/RestEnumerations.py

export const cotTypes = {
  "a-.-A": cotEntity["Air Air Track"],
  "a-.-A-C": cotEntity["Air Civ"],
  "a-.-A-C-F": cotEntity["Air Civ fixed"],
  "a-.-A-C-F-q": cotEntity["Air Civ fixed RPV, drone, UAV"],
  "a-.-A-C-H": cotEntity["Air Civ rotary"],
  "a-.-A-C-L": cotEntity["Air Civ Blimp"],
  "a-.-A-M": cotEntity["Air Mil"],
  "a-.-A-M-F": cotEntity["Air Mil Fixed"],
  "a-.-A-M-F-g": cotEntity["Air Mil Fixed Gunship"],
  "a-.-A-M-F-A": cotEntity["Air Mil Fixed Attack Strike"],
  "a-.-A-M-F-B": cotEntity["Air Mil Fixed Bomber"],
  "a-.-A-M-F-C": cotEntity["Air Mil Fixed Transport"],
  "a-.-A-M-F-C-H": cotEntity["Air Mil Fixed Transport Heavy"],
  "a-.-A-M-F-C-L": cotEntity["Air Mil Fixed Transport Light"],
  "a-.-A-M-F-C-M": cotEntity["Air Mil Fixed Transport Medium"],
  "a-.-A-M-F-D": cotEntity["Air Mil Fixed C2"],
  "a-.-A-M-F-F": cotEntity["Air Mil Fixed Fighter"],
  "a-.-A-M-F-F-I": cotEntity["Air Mil Fixed Interceptor"],
  "a-.-A-M-F-H": cotEntity["Air Mil Fixed CSAR"],
  "a-.-A-M-F-J": cotEntity["Air Mil Fixed ECM Jammer"],
  "a-.-A-M-F-K": cotEntity["Air Mil Fixed Tanker"],
  "a-.-A-M-F-L": cotEntity["Air Mil Fixed VSTOL"],
  "a-.-A-M-F-M": cotEntity["Air Mil Fixed SOF"],
  "a-.-A-M-F-O": cotEntity["Air Mil Fixed medevac"],
  "a-.-A-M-F-P": cotEntity["Air Mil Fixed Patrol"],
  "a-.-A-M-F-P-M": cotEntity["Air Mil Fixed Mine Countermeasures"],
  "a-.-A-M-F-P-N": cotEntity["Air Mil Fixed ASUW"],
  "a-.-A-M-F-Q": cotEntity["Air Mil Fixed Drone,RPV,UAV"],
  "a-.-A-M-F-R": cotEntity["Air Mil Fixed reconn"],
  "a-.-A-M-F-R-W": cotEntity["Air Mil Fixed AEW"],
  "a-.-A-M-F-R-X": cotEntity["Air Mil Fixed Photo"],
  "a-.-A-M-F-R-Z": cotEntity["Air Mil Fixed esm"],
  "a-.-A-M-F-S": cotEntity["Air Mil Fixed ASW Carrier Based"],
  "a-.-A-M-F-T": cotEntity["Air Mil Fixed Trainer"],
  "a-.-A-M-F-U": cotEntity["Air Mil Fixed Utility"],
  "a-.-A-M-F-U-H": cotEntity["Air Mil Fixed Utility Heavy"],
  "a-.-A-M-F-U-L": cotEntity["Air Mil Fixed Utility Light"],
  "a-.-A-M-F-U-M": cotEntity["Air Mil Fixed Utility Medium"],
  "a-.-A-M-F-Y": cotEntity["Air Mil Fixed C3I"],
  "a-.-A-M-H": cotEntity["Air Mil Rotor"],
  "a-.-A-M-H-C": cotEntity["Air Mil Rotor Transport"],
  "a-.-A-M-H-C-H": cotEntity["Air Mil Rotor Transport Heavy"],
  "a-.-A-M-H-C-L": cotEntity["Air Mil Rotor Transport Light"],
  "a-.-A-M-H-C-M": cotEntity["Air Mil Rotor Transport Medium"],
  "a-.-A-M-H-D": cotEntity["Air Mil Rotor C2"],
  "a-.-A-M-H-H": cotEntity["Air Mil Rotor CSAR"],
  "a-.-A-M-H-I": cotEntity["Air Mil Rotor Mine Countermeasures"],
  "a-.-A-M-H-J": cotEntity["Air Mil Rotor ECM Jammer"],
  "a-.-A-M-H-K": cotEntity["Air Mil Rotor Tanker"],
  "a-.-A-M-H-M": cotEntity["Air Mil Rotor SOF"],
  "a-.-A-M-H-O": cotEntity["Air Mil Rotor medevac"],
  "a-.-A-M-H-Q": cotEntity["Air Mil Rotor Drone,RPV,UAV"],
  "a-.-A-M-H-R": cotEntity["Air Mil Rotor Reconnaissance"],
  "a-.-A-M-H-S": cotEntity["Air Mil Rotor ASW MPA"],
  "a-.-A-M-H-T": cotEntity["Air Mil Rotor Trainer"],
  "a-.-A-M-H-U": cotEntity["Air Mil Rotor Utility"],
  "a-.-A-M-H-U-H": cotEntity["Air Mil Rotor Utility Heavy)"],
  "a-.-A-M-H-U-L": cotEntity["Air Mil Rotor Utility Light)"],
  "a-.-A-M-H-U-M": cotEntity["Air Mil Rotor Utility Medium)"],
  "a-.-A-M-L": cotEntity["Air Mil Blimp"],
  "a-.-A-W": cotEntity["Air Weapon"],
  "a-.-A-W-D": cotEntity["Air Weapon Decoy"],
  "a-.-A-W-M": cotEntity["Air Weapon Missile In Flight"],
  "a-.-A-W-M-A": cotEntity["Air Weapon Missile Air Launched"],
  "a-.-A-W-M-A-A": cotEntity["Air Weapon Missile Air To Air"],
  "a-.-A-W-M-A-S": cotEntity["Air Weapon Missile Air To Surface"],
  "a-.-A-W-M-L": cotEntity["Air Weapon Missile Attack Missile"],
  "a-.-A-W-M-S": cotEntity["Air Weapon Missile Land Launched Missile"],
  "a-.-A-W-M-S-A": cotEntity["Air Weapon Missile SAM"],
  "a-.-A-W-M-S-A-f": cotEntity["Air Weapon Missile SAM FixedSite"],
  "a-.-A-W-M-S-A-i": cotEntity["Air Weapon Missile SAM Manpad"],
  "a-.-A-W-M-S-A-m": cotEntity["Air Weapon Missile SAM Mobile"],
  "a-.-A-W-M-S-S": cotEntity["Air Weapon Missile Surface To Surface (SSM)"],
  "a-.-A-W-M-U": cotEntity["Air Weapon Missile Subsurface To Surface (S SSM)"],
  "a-.-G": cotEntity["Ground"],
  "a-.-G-E": cotEntity["Gnd Equipment"],
  "a-.-G-E-S": cotEntity["Gnd Equip Sensor"],
  "a-.-G-E-S-E": cotEntity["Gnd Equip Sensor Emplaced"],
  "a-.-G-E-S-R": cotEntity["Gnd Equip Sensor Radar"],
  "a-.-G-E-V": cotEntity["Gnd Equip Vehicle"],
  "a-.-G-E-V-A": cotEntity["Gnd Equip Vehic Armor Gun"],
  "a-.-G-E-V-A-A": cotEntity["Gnd Equip Vehic Armor APC"],
  "a-.-G-E-V-A-A-R": cotEntity["Gnd Equip Vehic Armor APC Recovery"],
  "a-.-G-E-V-A-C": cotEntity["Gnd Equip Vehic Armor C2V ACV"],
  "a-.-G-E-V-A-I": cotEntity["Gnd Equip Vehic Armor Infantry"],
  "a-.-G-E-V-A-L": cotEntity["Gnd Equip Vehic Armor Light"],
  "a-.-G-E-V-A-S": cotEntity["Gnd Equip Vehic Armor Combat Service Support"],
  "a-.-G-E-V-A-T": cotEntity["Gnd Equip Vehic Armor Tank"],
  "a-.-G-E-V-A-T-H": cotEntity["Gnd Equip Vehic Armor Tank Heavy"],
  "a-.-G-E-V-A-T-H-R": cotEntity["Gnd Equip Vehic Armor Tank Heavy Recovery"],
  "a-.-G-E-V-A-T-L": cotEntity["Gnd Equip Vehic Armor Tank Light"],
  "a-.-G-E-V-A-T-L-R": cotEntity["Gnd Equip Vehic Armor Tank Light Recovery"],
  "a-.-G-E-V-A-T-M": cotEntity["Gnd Equip Vehic Armor Tank Medium"],
  "a-.-G-E-V-C": cotEntity["Gnd Equip Vehic Civilian"],
  "a-.-G-E-V-E": cotEntity["Gnd Equip Vehic Engineer"],
  "a-.-G-E-V-E-A": cotEntity["Gnd Equip Vehic Mine Clearing Vehicle"],
  "a-.-G-E-V-E-A-A": cotEntity["Gnd Equip Vehic Armored Mounted Mine Clearing Vehicle"],
  "a-.-G-E-V-E-A-T": cotEntity["Gnd Equip Vehic Trailer Mounted Mine Clearing Vehicle"],
  "a-.-G-E-V-E-B": cotEntity["Gnd Equip Vehic Bridge"],
  "a-.-G-E-V-E-C": cotEntity["Gnd Equip Vehic Construction"],
  "a-.-G-E-V-E-D": cotEntity["Gnd Equip Vehic Dozer"],
  "a-.-G-E-V-E-E": cotEntity["Gnd Equip Vehic Earthmover"],
  "a-.-G-E-V-E-M": cotEntity["Gnd Equip Vehic Mine Laying Vehicle"],
  "a-.-G-E-V-U-B": cotEntity["Gnd Equip Vehic Bus"],
  "a-.-G-E-V-U-L": cotEntity["Gnd Equip Vehic Limited Cross Country Truck"],
  "a-.-G-E-V-U-R": cotEntity["Gnd Equip Vehic Boat"],
  "a-.-G-E-V-U-R-l": cotEntity["Gnd Equip Vehic Boat Large"],
  "a-.-G-E-V-U-R-m": cotEntity["Gnd Equip Vehic Boat Med"],
  "a-.-G-E-V-U-R-s": cotEntity["Gnd Equip Vehic Boat Small"],
  "a-.-G-E-V-U-S": cotEntity["Gnd Equip Vehic Semi"],
  "a-.-G-E-V-U-X": cotEntity["Gnd Equip Vehic Cross Country Truck"],
  "a-.-G-E-V-m": cotEntity["Gnd Equip Vehic Ambulance"],
  "a-.-G-E-W": cotEntity["Gnd Equip Weapon"],
  "a-.-G-E-W-A": cotEntity["Gnd Equip Weapon Air Defense Gun"],
  "a-.-G-E-W-D": cotEntity["Gnd Equip Weapon DirectFire "],
  "a-.-G-E-W-D-H-S": cotEntity["Gnd Equip Weapon DirectFire Heavy Self Propelled"],
  "a-.-G-E-W-D-L": cotEntity["Gnd Equip Weapon DirectFire Light"],
  "a-.-G-E-W-D-L-S": cotEntity["Gnd Equip Weapon DirectFire Light Self Propelled"],
  "a-.-G-E-W-D-M": cotEntity["Gnd Equip Weapon DirectFire Medium"],
  "a-.-G-E-W-D-M-S": cotEntity["Gnd Equip Weapon DirectFire Medium Self Propelled"],
  "a-.-G-E-W-G": cotEntity["Gnd Equip Weapon AntiTankGun"],
  "a-.-G-E-W-G-L": cotEntity["Gnd Equip Weapon Atg Light"],
  "a-.-G-E-W-G-M": cotEntity["Gnd Equip Weapon Atg Medium"],
  "a-.-G-E-W-G-R": cotEntity["Gnd Equip Weapon Atg Recoilless"],
  "a-.-G-E-W-H": cotEntity["Gnd Equip Weapon Howitzer"],
  "a-.-G-E-W-M": cotEntity["Gnd Equip Weapon MissileLauncher"],
  "a-.-G-E-W-O": cotEntity["Gnd Equip Weapon Mortar"],
  "a-.-G-E-W-R": cotEntity["Gnd Equip Weapon Rifle Automatic Weapon"],
  "a-.-G-E-W-R-R": cotEntity["Gnd Equip Weapon Rifle Rifle"],
  "a-.-G-E-W-S": cotEntity["Gnd Equip Weapon RocketLauncher Single "],
  "a-.-G-E-W-T": cotEntity["Gnd Equip Weapon RocketLauncher AntiTank"],
  "a-.-G-E-W-Z": cotEntity["Gnd Equip Weapon Grenade Launcher"],
  "a-.-G-E-X": cotEntity["Gnd Equip Special Equipment"],
  "a-.-G-E-X-F": cotEntity["Gnd Equip Flame Thrower"],
  "a-.-G-E-X-L": cotEntity["Gnd Equip Laser"],
  "a-.-G-E-X-M": cotEntity["Gnd Equip Land Mines"],
  "a-.-G-E-X-M-C": cotEntity["Gnd Equip Claymore"],
  "a-.-G-E-X-M-L": cotEntity["Gnd Equip Less Than Lethal"],
  "a-.-G-E-X-N": cotEntity["Gnd Equip NBC Equipment"],
  "a-.-G-I": cotEntity["Gnd Building"],
  "a-.-G-I-B": cotEntity["Gnd Structure Base Military"],
  "a-.-G-I-B-A": cotEntity["Gnd Structure Base Airbase"],
  "a-.-G-I-B-N": cotEntity["Gnd Structure Base Naval Base"],
  "a-.-G-I-c": cotEntity["Gnd Structure Civilian"],
  "a-.-G-I-c-b": cotEntity["Gnd Structure Civilian Bridge"],
  "a-.-G-I-c-bar": cotEntity["Gnd Structure Civilian Fence or Wall or Barrier"],
  "a-.-G-I-c-can": cotEntity["Gnd Structure Civilian Canal"],
  "a-.-G-I-c-can-l": cotEntity["Gnd Structure Civilian Canal Lock"],
  "a-.-G-I-c-frm": cotEntity["Gnd Structure Civilian Farm"],
  "a-.-G-I-c-mon": cotEntity["Gnd Structure Civilian Monument"],
  "a-.-G-I-c-o": cotEntity["Gnd Structure Civilian Offices"],
  "a-.-G-I-c-rah": cotEntity["Gnd Structure Civilian Residence or Apartment or Hotel"],
  "a-.-G-I-c-ret": cotEntity["Gnd Structure Civilian Retail"],
  "a-.-G-I-c-sch": cotEntity["Gnd Structure Civilian School"],
  "a-.-G-I-c-vip": cotEntity["Gnd Structure Civilian vip"],
  "a-.-G-I-c-whs": cotEntity["Gnd Structure Civilian Warehouse"],
  "a-.-G-I-E": cotEntity["Gnd Structure Factory"],
  "a-.-G-I-G": cotEntity["Gnd Structure Government"],
  "a-.-G-I-i": cotEntity["Gnd Structure IM Facilities"],
  "a-.-G-I-i-e": cotEntity["Gnd Structure IM Facilities Emergency Management"],
  "a-.-G-I-i-e-EOC": cotEntity["Gnd Structure IM Facilities Emergency Management Emergency Operations Center"],
  "a-.-G-I-i-e-ic": cotEntity["Gnd Structure IM Facilities Emergency Management Incident Commander"],
  "a-.-G-I-i-e-icc": cotEntity["Gnd Structure IM Facilities Emergency Management Incident Communications Center"],
  "a-.-G-I-i-e-icp": cotEntity["Gnd Structure IM Facilities Emergency Management Incident Command Post"],
  "a-.-G-I-i-e-wr": cotEntity["Gnd Structure IM Facilities Emergency Management War Room"],
  "a-.-G-I-i-f": cotEntity["Gnd Structure IM Facilities Fire and Hazmat"],
  "a-.-G-I-i-f-fd": cotEntity["Gnd Structure IM Facilities Fire and Hazmat Fire Department"],
  "a-.-G-I-i-h": cotEntity["Gnd Structure IM Facilities Health and Medical"],
  "a-.-G-I-i-h-md": cotEntity["Gnd Structure IM Facilities Health and Medical Medical Dispatch"],
  "a-.-G-I-i-l": cotEntity["Gnd Structure IM Facilities Law Enforcement"],
  "a-.-G-I-i-l-cp": cotEntity["Gnd Structure IM Facilities Law Enforcement Police Checkpoint"],
  "a-.-G-I-i-l-hp": cotEntity["Gnd Structure IM Facilities Law Enforcement Highway Patrol"],
  "a-.-G-I-i-l-lp": cotEntity["Gnd Structure IM Facilities Law Enforcement Local Police"],
  "a-.-G-I-i-l-ntz": cotEntity["Gnd Structure IM Facilities Law Enforcement No Trespassing Zone"],
  "a-.-G-I-i-l-sd": cotEntity["Gnd Structure IM Facilities Law Enforcement Sheriffs Department"],
  "a-.-G-I-i-l-SP": cotEntity["Gnd Structure IM Facilities Law Enforcement State Police"],
  "a-.-G-I-i-m": cotEntity["Gnd Structure IM Facilities Emergency Medical Services"],
  "a-.-G-I-i-o": cotEntity["Gnd Structure IM Facilities Other"],
  "a-.-G-I-i-o-AD": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch"],
  "a-.-G-I-i-o-AD-ems": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch ems"],
  "a-.-G-I-i-o-AD-f": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Fire"],
  "a-.-G-I-i-o-AD-hwy": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Highway"],
  "a-.-G-I-i-o-AD-mda": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Media"],
  "a-.-G-I-i-o-AD-pl": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Police Local"],
  "a-.-G-I-i-o-AD-ps": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Police Station"],
  "a-.-G-I-i-o-AD-tow": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Tow"],
  "a-.-G-I-i-o-AD-ts": cotEntity["Gnd Structure IM Facilities Other Agency Dispatch Transit"],
  "a-.-G-I-i-o-bcc": cotEntity["Gnd Structure IM Facilities Other Border Control Checkpoint"],
  "a-.-G-I-i-o-dmz": cotEntity["Gnd Structure IM Facilities Other dmz"],
  "a-.-G-I-i-o-isp": cotEntity["Gnd Structure IM Facilities Other Independent Service Provider"],
  "a-.-G-I-i-o-mc": cotEntity["Gnd Structure IM Facilities Other Mobile Center"],
  "a-.-G-I-i-o-mc-f": cotEntity["Gnd Structure IM Facilities Other Mobile Center Fire"],
  "a-.-G-I-i-o-mc-h": cotEntity["Gnd Structure IM Facilities Other Mobile Center Medical"],
  "a-.-G-I-i-o-mc-l": cotEntity["Gnd Structure IM Facilities Other Mobile Center Law Enforcement"],
  "a-.-G-I-i-o-mes": cotEntity["Gnd Structure IM Facilities Other Message Center"],
  "a-.-G-I-i-o-mob": cotEntity["Gnd Structure IM Facilities Other Mobilization Center"],
  "a-.-G-I-i-o-mob-ems": cotEntity["Gnd Structure IM Facilities Other Mobilization Center ems"],
  "a-.-G-I-i-o-mob-es": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Transit"],
  "a-.-G-I-i-o-mob-f": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Fire"],
  "a-.-G-I-i-o-mob-hwy": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Highway"],
  "a-.-G-I-i-o-mob-mda": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Media"],
  "a-.-G-I-i-o-mob-pl": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Police Local"],
  "a-.-G-I-i-o-mob-ps": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Police Station"],
  "a-.-G-I-i-o-mob-tow": cotEntity["Gnd Structure IM Facilities Other Mobilization Center Tow"],
  "a-.-G-I-i-o-ps": cotEntity["Gnd Structure IM Facilities Other Public Safety"],
  "a-.-G-I-i-o-rl": cotEntity["Gnd Structure IM Facilities Other Reporting Locations"],
  "a-.-G-I-i-o-sa": cotEntity["Gnd Structure IM Facilities Other Staging Area"],
  "a-.-G-I-i-o-sa-ems": cotEntity["Gnd Structure IM Facilities Other Staging Area ems"],
  "a-.-G-I-i-o-sa-f": cotEntity["Gnd Structure IM Facilities Other Staging Area Fire"],
  "a-.-G-I-i-o-sa-hwy": cotEntity["Gnd Structure IM Facilities Other Staging Area Highway"],
  "a-.-G-I-i-o-sa-mda": cotEntity["Gnd Structure IM Facilities Other Staging Area Media"],
  "a-.-G-I-i-o-sa-pl": cotEntity["Gnd Structure IM Facilities Other Staging Area Police Local"],
  "a-.-G-I-i-o-sa-ps": cotEntity["Gnd Structure IM Facilities Other Staging Area Police Station"],
  "a-.-G-I-i-o-sa-tow": cotEntity["Gnd Structure IM Facilities Other Staging Area Tow"],
  "a-.-G-I-i-o-sa-ts": cotEntity["Gnd Structure IM Facilities Other Staging Area Transit"],
  "a-.-G-I-i-o-sc": cotEntity["Gnd Structure IM Facilities Other Security Checkpoint"],
  "a-.-G-I-i-o-seg": cotEntity["Gnd Structure IM Facilities Other Segment"],
  "a-.-G-I-i-o-t": cotEntity["Gnd Structure IM Facilities Other Transportation"],
  "a-.-G-I-i-o-t-IM": cotEntity["Gnd Structure IM Facilities Other Transportation Transit Incident Management Center"],
  "a-.-G-I-i-o-t-tc": cotEntity["Gnd Structure IM Facilities Other Transportation Transit Management Center"],
  "a-.-G-I-i-o-t-td": cotEntity["Gnd Structure IM Facilities Other Transportation Traffic Inc Service Patrol Dispatch"],
  "a-.-G-I-i-o-t-tm": cotEntity["Gnd Structure IM Facilities Other Transportation Traffic Management Center"],
  "a-.-G-I-i-o-tmp": cotEntity["Gnd Structure IM Facilities Other Temp"],
  "a-.-G-I-i-o-tmp-f": cotEntity["Gnd Structure IM Facilities Other Temp Fire"],
  "a-.-G-I-i-o-tmp-h": cotEntity["Gnd Structure IM Facilities Other Temp Medical"],
  "a-.-G-I-i-o-tmp-l": cotEntity["Gnd Structure IM Facilities Other Temp Law Enforcement"],
  "a-.-G-I-i-p": cotEntity["Gnd Structure IM Facilities Public Works"],
  "a-.-G-I-M": cotEntity["Gnd Structure Mil Military Materiel Facility"],
  "a-.-G-I-M-A": cotEntity["Gnd Structure Mil Aircraft Production"],
  "a-.-G-I-M-C": cotEntity["Gnd Structure Mil NBC Warfare Production"],
  "a-.-G-I-M-E": cotEntity["Gnd Structure Mil Ammunition Production"],
  "a-.-G-I-M-F": cotEntity["Gnd Structure Mil Nuclear Energy"],
  "a-.-G-I-M-F-A": cotEntity["Gnd Structure Mil Atomic Energy Reactor"],
  "a-.-G-I-M-F-P": cotEntity["Gnd Structure Mil Nuclear Material Production"],
  "a-.-G-I-M-F-P-W": cotEntity["Gnd Structure Mil Nuclear Weapons Grade"],
  "a-.-G-I-M-F-S": cotEntity["Gnd Structure Mil Nuclear Material Storage"],
  "a-.-G-I-M-G": cotEntity["Gnd Structure Mil Armament Production"],
  "a-.-G-I-M-M": cotEntity["Gnd Structure Mil Missile+Space System Production"],
  "a-.-G-I-M-N": cotEntity["Gnd Structure Mil Engineering Equipment Production"],
  "a-.-G-I-M-N-B": cotEntity["Gnd Structure Mil Bridge"],
  "a-.-G-I-M-N-B-l": cotEntity["Gnd Structure Mil Bridge Large"],
  "a-.-G-I-M-N-B-m": cotEntity["Gnd Structure Mil Bridge Med"],
  "a-.-G-I-M-N-B-s": cotEntity["Gnd Structure Mil Bridge Small"],
  "a-.-G-I-M-N-c": cotEntity["Gnd Structure Mil Canal"],
  "a-.-G-I-M-S": cotEntity["Gnd Structure Mil Ship Construction"],
  "a-.-G-I-M-V": cotEntity["Gnd Structure Mil Military Vehicle Production"],
  "a-.-G-I-P": cotEntity["Gnd Structure Processing Facility"],
  "a-.-G-I-P-D": cotEntity["Gnd Structure Decon"],
  "a-.-G-I-R": cotEntity["Gnd Structure Raw Material Production Storage"],
  "a-.-G-I-R-M": cotEntity["Gnd Structure Mine"],
  "a-.-G-I-R-N": cotEntity["Gnd Structure NBC"],
  "a-.-G-I-R-N-B": cotEntity["Gnd Structure Biological"],
  "a-.-G-I-R-N-C": cotEntity["Gnd Structure Chemical"],
  "a-.-G-I-R-N-N": cotEntity["Gnd Structure Nuclear"],
  "a-.-G-I-R-P": cotEntity["Gnd Structure petroleum gas oil"],
  "a-.-G-I-R-P-r": cotEntity["Gnd Structure petroleum gas oil Refinery"],
  "a-.-G-I-T": cotEntity["Gnd Structure Transport Facility"],
  "a-.-G-I-T-a": cotEntity["Gnd Structure Transport Facility Airport"],
  "a-.-G-I-T-hb": cotEntity["Gnd Structure Transport Facility Helibase"],
  "a-.-G-I-T-hs": cotEntity["Gnd Structure Transport Facility Helispot"],
  "a-.-G-I-T-l": cotEntity["Gnd Structure Transport Facility Land Port"],
  "a-.-G-I-T-pg": cotEntity["Gnd Structure Transport Facility Parking Garage"],
  "a-.-G-I-T-r": cotEntity["Gnd Structure Transport Facility Railroad"],
  "a-.-G-I-T-s": cotEntity["Gnd Structure Transport Facility Seaport"],
  "a-.-G-I-U": cotEntity["Gnd Structure Utility Service, Research, Utility Facility"],
  "a-.-G-I-U-E": cotEntity["Gnd Structure Utility Electric Power"],
  "a-.-G-I-U-E-c": cotEntity["Gnd Structure Utility Electric Power Coal Power Plant"],
  "a-.-G-I-U-E-h": cotEntity["Gnd Structure Utility Electric Power Hydroelectric Power Plant"],
  "a-.-G-I-U-E-o": cotEntity["Gnd Structure Utility Electric Power Other Power"],
  "a-.-G-I-U-E-ps": cotEntity["Gnd Structure Utility Electric Power Power Substation"],
  "a-.-G-I-U-E-D": cotEntity["Gnd Structure Utility Dam"],
  "a-.-G-I-U-E-F": cotEntity["Gnd Structure Utility Fossil Fuel"],
  "a-.-G-I-U-E-N": cotEntity["Gnd Structure Utility Nuclear Plant"],
  "a-.-G-I-U-P": cotEntity["Gnd Structure Utility Public Water Services"],
  "a-.-G-I-U-R": cotEntity["Gnd Structure Utility Technological Research"],
  "a-.-G-I-U-T": cotEntity["Gnd Structure Utility Telecommunications"],
  "a-.-G-I-U-T-com": cotEntity["Gnd Structure Utility Telecommunications Communications"],
  "a-.-G-I-U-T-com-af": cotEntity["Gnd Structure Utility Telecommunications Communications Antenna Farm"],
  "a-.-G-I-U-T-com-sat": cotEntity["Gnd Structure Utility Telecommunications Communications Satellite Communications"],
  "a-.-G-I-U-T-com-tow": cotEntity["Gnd Structure Utility Telecommunications Communications Tower"],
  "a-.-G-I-U-T-r": cotEntity["Gnd Structure Utility Telecommunications Radio"],
  "a-.-G-I-U-T-r-s": cotEntity["Gnd Structure Utility Telecommunications Radio Station"],
  "a-.-G-I-U-T-tp": cotEntity["Gnd Structure Utility Telecommunications Telephone"],
  "a-.-G-I-U-T-tv": cotEntity["Gnd Structure Utility Telecommunications Television"],
  "a-.-G-I-U-T-tv-c": cotEntity["Gnd Structure Utility Telecommunications Television Cable"],
  "a-.-G-I-U-T-tv-s": cotEntity["Gnd Structure Utility Telecommunications Television Station"],
  "a-.-G-I-X": cotEntity["Gnd Structure Medical Facility"],
  "a-.-G-I-X-H": cotEntity["Gnd Structure Hospital"],
  "a-.-G-I-X-hcf": cotEntity["Gnd Structure Medical Facility Hospital Hospital Care Facility"],
  "a-.-G-I-r": cotEntity["Gnd Structure Road"],
  "a-.-G-I-r-h": cotEntity["Gnd Structure Road Highway"],
  "a-.-G-I-r-i": cotEntity["Gnd Structure Road Improved"],
  "a-.-G-I-r-ra": cotEntity["Gnd Structure Road Rest Area"],
  "a-.-G-I-r-u": cotEntity["Gnd Structure Road Unimproved"],
  "a-.-G-U-C-A": cotEntity["Gnd Combat armor"],
  "a-.-G-U-C-A-A": cotEntity["Gnd Combat Armor anti armor"],
  "a-.-G-U-C-A-W": cotEntity["Gnd Combat Armor armor, wheeled"],
  "a-.-G-U-C-A-W-W-R": cotEntity["Gnd Combat Armor armor, wheeled amphibious recovery"],
  "a-.-G-U-C-D": cotEntity["Gnd Combat Defense air defense"],
  "a-.-G-U-C-D-T": cotEntity["Gnd Combat Defense targeting unit"],
  "a-.-G-U-C-E": cotEntity["Gnd Combat Engineer engineer"],
  "a-.-G-U-C-F": cotEntity["Gnd Combat Artillery (Fixed)"],
  "a-.-G-U-C-F-S-A": cotEntity["Gnd Combat airborne"],
  "a-.-G-U-C-F-S-L": cotEntity["Gnd Combat light"],
  "a-.-G-U-C-F-S-O": cotEntity["Gnd Combat mountain"],
  "a-.-G-U-C-F-S-S": cotEntity["Gnd Combat air assault"],
  "a-.-G-U-C-I": cotEntity["Gnd Combat Infantry Troops (Open)"],
  "a-.-G-U-C-I-A": cotEntity["Gnd Combat Infantry Airborne"],
  "a-.-G-U-C-I-C": cotEntity["Gnd Combat Infantry Arctic"],
  "a-.-G-U-C-I-I": cotEntity["Gnd Combat Infantry Fighting Vehicle"],
  "a-.-G-U-C-I-S": cotEntity["Gnd Combat Infantry Air Assault"],
  "a-.-G-U-C-I-Z": cotEntity["Gnd Combat Infantry Mechanized"],
  "a-.-G-U-C-I-d": cotEntity["Gnd Combat Infantry DugIn"],
  "a-.-G-U-C-R": cotEntity["Gnd Combat Recon "],
  "a-.-G-U-U-I": cotEntity["Gnd information warfare unit"],
  "a-.-G-U-U-L": cotEntity["Gnd law enforcement unit"],
  "a-.-G-U-U-L-C": cotEntity["Gnd civilian law enforcement"],
  "a-.-G-U-U-L-D": cotEntity["Gnd central intelligence division (CID)"],
  "a-.-G-U-U-L-F": cotEntity["Gnd security police (air)"],
  "a-.-G-U-U-L-M": cotEntity["Gnd military police"],
  "a-.-G-U-U-M-C": cotEntity["Gnd counter intelligence"],
  "a-.-G-U-U-M-J": cotEntity["Gnd joint intelligence center"],
  "a-.-G-U-U-M-M-O": cotEntity["Gnd meteorological"],
  "a-.-G-U-U-M-O": cotEntity["Gnd operations"],
  "a-.-G-U-U-M-Q": cotEntity["Gnd interrogation"],
  "a-.-G-U-U-M-R": cotEntity["Gnd surveillance"],
  "a-.-G-U-i": cotEntity["Gnd IM Resources"],
  "a-.-G-U-i-a": cotEntity["Gnd IM Resources Animal Health"],
  "a-.-G-U-i-a-imt": cotEntity["Gnd Incident Management Team Animal Protection"],
  "a-.-G-U-i-e": cotEntity["Gnd IM Resources Emergency Management"],
  "a-.-G-U-i-e-mfk": cotEntity["Gnd Mobile Feeding Kitchen"],
  "a-.-G-U-i-e-pac": cotEntity["Gnd Public Assistance Coordinator"],
  "a-.-G-U-i-e-rna": cotEntity["Gnd Rapid Needs Assessment Team"],
  "a-.-G-U-i-e-smt": cotEntity["Gnd Shelter Management Team"],
  "a-.-G-U-i-e-val": cotEntity["Gnd Volunteer Agency Liaison"],
  "a-.-G-U-i-m": cotEntity["Gnd IM Resources Emergency Medical Services"],
  "a-.-G-U-i-m-ag": cotEntity["Gnd Ambulances (Ground)"],
  "a-.-G-U-i-m-ast": cotEntity["Gnd Ambulance Strike Team"],
  "a-.-G-U-i-m-atf": cotEntity["Gnd Ambulance Task Force"],
  "a-.-G-U-i-m-etf": cotEntity["Gnd Emergency Medical Task Force"],
  "a-.-G-U-i-f": cotEntity["Gnd IM Resources Fire hazmat"],
  "a-.-G-U-i-f-act": cotEntity["Gnd Area Command Team, Firefighting"],
  "a-.-G-U-i-f-bp": cotEntity["Gnd Brush Patrol"],
  "a-.-G-U-i-f-ct": cotEntity["Gnd Crew Transport"],
  "a-.-G-U-i-f-efp": cotEntity["Gnd Engine, Fire (Pumper)"],
  "a-.-G-U-i-f-fb": cotEntity["Gnd Fire Boat"],
  "a-.-G-U-i-f-ft": cotEntity["Gnd Fuel Tender"],
  "a-.-G-U-i-f-fta": cotEntity["Gnd Fire Truck"],
  "a-.-G-U-i-f-ftf": cotEntity["Gnd Foam Tender"],
  "a-.-G-U-i-f-hc": cotEntity["Gnd Hand Crew"],
  "a-.-G-U-i-f-hf": cotEntity["Gnd Helicopters Firefighting"],
  "a-.-G-U-i-f-ht": cotEntity["Gnd Helitanker "],
  "a-.-G-U-i-f-mcu": cotEntity["Gnd Mobile Communications Unit"],
  "a-.-G-U-i-f-nsf": cotEntity["Gnd USCG National Strike Force"],
  "a-.-G-U-i-f-pp": cotEntity["Gnd Portable Pump"],
  "a-.-G-U-i-f-st": cotEntity["Gnd Strike Team, Engine (Fire)"],
  "a-.-G-U-i-f-wt": cotEntity["Gnd Water Tender, Firefighting (Tanker)"],
  "a-.-G-U-i-h": cotEntity["Gnd IM Resources Health and Medical"],
  "a-.-G-U-i-h-dmb": cotEntity["Gnd Disaster Medical Assistance Team - Basic"],
  "a-.-G-U-i-h-mst": cotEntity["Gnd NDMS Management Support Team"],
  "a-.-G-U-i-l": cotEntity["Gnd IM Resources Law Enforcement"],
  "a-.-G-U-i-l-bs": cotEntity["Gnd Bomb Squad Explosives Team"],
  "a-.-G-U-i-l-cct": cotEntity["Gnd Crowd Control Team"],
  "a-.-G-U-i-l-dt": cotEntity["Gnd Public Safety Dive Team"],
  "a-.-G-U-i-l-hps": cotEntity["Gnd Aviation-Helicopters Patrol Surveillance"],
  "a-.-G-U-i-l-oa": cotEntity["Gnd Observation Aircraft"],
  "a-.-G-U-i-l-tt": cotEntity["Gnd SWAT Tactical Team"],
  "a-.-G-U-i-p": cotEntity["Gnd IM Resources Public Works"],
  "a-.-G-U-i-p-acf": cotEntity["Gnd Air Curtain Burners (Above Ground)"],
  "a-.-G-U-i-p-ach": cotEntity["Gnd Air Conditioner Heater"],
  "a-.-G-U-i-p-act": cotEntity["Gnd Air Curtain Burners (In Ground)"],
  "a-.-G-U-i-p-atc": cotEntity["Gnd All Terrain Cranes"],
  "a-.-G-U-i-p-bh": cotEntity["Gnd Backhoe Loader"],
  "a-.-G-U-i-p-cah": cotEntity["Gnd Chillers Air Handlers"],
  "a-.-G-U-i-p-cc": cotEntity["Gnd Crawler Cranes"],
  "a-.-G-U-i-p-dat": cotEntity["Gnd Disaster Assessment Team"],
  "a-.-G-U-i-p-dmm": cotEntity["Gnd Debris Management Monitoring Team"],
  "a-.-G-U-i-p-dmr": cotEntity["Gnd Debris Management Site Reduction Team"],
  "a-.-G-U-i-p-dmt": cotEntity["Gnd Debris Management Team"],
  "a-.-G-U-i-p-drt": cotEntity["Gnd Disaster Recovery Team"],
  "a-.-G-U-i-p-dt": cotEntity["Gnd Dump Trailer"],
  "a-.-G-U-i-p-dtf": cotEntity["Gnd Dump Truck Off Road"],
  "a-.-G-U-i-p-dtn": cotEntity["Gnd Dump Truck On Road"],
  "a-.-G-U-i-p-epr": cotEntity["Gnd Electrical Power Restoration Team"],
  "a-.-G-U-i-p-es": cotEntity["Gnd Engineering Services"],
  "a-.-G-U-i-p-fbt": cotEntity["Gnd Flat Bed Trailer Truck"],
  "a-.-G-U-i-p-gen": cotEntity["Gnd Generators "],
  "a-.-G-U-i-p-hel": cotEntity["Gnd Hydraulic Excavator (Large)"],
  "a-.-G-U-i-p-hem": cotEntity["Gnd Hydraulic Excavator (Medium)"],
  "a-.-G-U-i-p-htc": cotEntity["Gnd Hydraulic Truck Cranes"],
  "a-.-G-U-i-p-ltc": cotEntity["Gnd Lattice Truck Cranes"],
  "a-.-G-U-i-p-tb": cotEntity["Gnd Tug Boat"],
  "a-.-G-U-i-p-td": cotEntity["Gnd Track Dozer"],
  "a-.-G-U-i-p-tg": cotEntity["Gnd Tub Grinder"],
  "a-.-G-U-i-p-tt": cotEntity["Gnd Tractor Trailer"],
  "a-.-G-U-i-p-wd": cotEntity["Gnd Wheel Dozer"],
  "a-.-G-U-i-p-wpt": cotEntity["Gnd Water Purification Team"],
  "a-.-G-U-i-p-wt": cotEntity["Gnd Water Truck"],
  "a-.-G-U-i-s": cotEntity["Gnd IM Resources Search and Rescue"],
  "a-.-G-U-i-s-ar": cotEntity["Gnd Airborne Reconnaissance"],
  "a-.-G-U-i-s-ast": cotEntity["Gnd Air Search Team"],
  "a-.-G-U-i-s-cas": cotEntity["Gnd Canine SAR Team Avalanche Snow"],
  "a-.-G-U-i-s-rdf": cotEntity["Gnd Radio Direction Finding Team"],
  "a-.-G-U-i-s-sfd": cotEntity["Gnd Swiftwater Flood Search and Dive Rescue Team"],
  "a-.-G-U-i-s-uis": cotEntity["Gnd USAR Incident Support Team"],
  "a-.-G-U-i-s-utf": cotEntity["Gnd USAR Task Force"],
  "a-.-G-U-i-s-wi": cotEntity["Gnd Wilderness SAR Team"],
  "a-.-G-U-i-o": cotEntity["Gnd IM Resources Other"],
  "a-.-S": cotEntity["Surface sea surface track"],
  "a-.-S-C": cotEntity["Surface combatant"],
  "a-.-S-C-A": cotEntity["Surface amphibious warfare ship"],
  "a-.-S-C-H": cotEntity["Surface hovercraft"],
  "a-.-S-C-L": cotEntity["Surface line"],
  "a-.-S-C-L-B-B": cotEntity["Surface battleship"],
  "a-.-S-C-L-C-C": cotEntity["Surface cruiser"],
  "a-.-S-C-L-C-V": cotEntity["Surface carrier"],
  "a-.-S-C-L-D-D": cotEntity["Surface destroyer"],
  "a-.-S-C-L-F-F": cotEntity["Surface frigate corvette"],
  "a-.-S-C-M": cotEntity["Surface mine warfare vessel"],
  "a-.-S-C-M-M-A": cotEntity["Surface MCM support"],
  "a-.-S-C-M-M-D": cotEntity["Surface MCM drone"],
  "a-.-S-C-M-M-H": cotEntity["Surface minehunter"],
  "a-.-S-C-M-M-L": cotEntity["Surface minelayer"],
  "a-.-S-C-M-M-S": cotEntity["Surface minesweeper"],
  "a-.-S-C-P": cotEntity["Surface patrol"],
  "a-.-S-C-P-S-B": cotEntity["Surface antisubmarine warfare"],
  "a-.-S-C-P-S-U": cotEntity["Surface antisurface warfare"],
  "a-.-S-N": cotEntity["Surface noncombatant"],
  "a-.-S-X-F": cotEntity["Surface fishing"],
  "a-.-S-X-M": cotEntity["Surface merchant"],
  "a-.-S-X-M-C": cotEntity["Surface cargo"],
  "a-.-S-X-M-F": cotEntity["Surface ferry"],
  "a-.-S-X-M-O": cotEntity["Surface oiler tanker"],
  "a-.-S-X-M-P": cotEntity["Surface passenger"],
  "a-.-S-X-M-T-U": cotEntity["Surface tug"],
  "a-.-S-X-R": cotEntity["Surface leisure craft"],
  "a-.-U-N-D": cotEntity["SubSurf diver"],
  "a-.-U-S": cotEntity["SubSurf submarine"],
  "a-.-X": cotEntity["Other"],
  "a-.-X-i": cotEntity["Other incident"],
  "a-.-X-i-g": cotEntity["Other incident geo"],
  "a-.-X-i-g-a": cotEntity["Other incident geo avalanche"],
  "a-.-X-i-g-e": cotEntity["Other incident geo earthquake"],
  "a-.-X-i-g-l": cotEntity["Other incident geo landslide"],
  "a-.-X-i-g-s": cotEntity["Other incident geo subsistance"],
  "a-.-X-i-g-v": cotEntity["Other incident geo volcano"],
  "a-.-X-i-g-v-e": cotEntity["Other incident geo eruption"],
  "a-.-X-i-m": cotEntity["Other incident met"],
  "a-.-X-i-m-z": cotEntity["Other incident met drizzle"],
  "a-.-X-i-m-d": cotEntity["Other incident met drought"],
  "a-.-X-i-m-f": cotEntity["Other incident met flood"],
  "a-.-X-i-m-g": cotEntity["Other incident met fog"],
  "a-.-X-i-m-h": cotEntity["Other incident met hail"],
  "a-.-X-i-m-r": cotEntity["Other incident met rain"],
  "a-.-X-i-m-a": cotEntity["Other incident met sandstorm"],
  "a-.-X-i-m-s": cotEntity["Other incident met snow"],
  "a-.-X-i-m-u": cotEntity["Other incident metthunderstorm"],
  "a-.-X-i-m-t": cotEntity["Other incident met tornado"],
  "a-.-X-i-m-c": cotEntity["Other incident met cyclone"],
  "a-.-X-i-m-n": cotEntity["Other incident met tsunami"],
  "a-.-X-i-s": cotEntity["Other incident safety"],
  "a-.-X-i-l": cotEntity["Other incident security"],
  "a-.-X-i-l-c": cotEntity["Other incident security civil disturb"],
  "a-.-X-i-l-c-d": cotEntity["Other incident security civil disturb demonstration"],
  "a-.-X-i-l-c-p": cotEntity["Other incident security civil disturb displaced"],
  "a-.-X-i-l-c-r": cotEntity["Other incident security civil disturb rioting"],
  "a-.-X-i-l-l": cotEntity["Other incident security law enforcement"],
  "a-.-X-i-l-l-b": cotEntity["Other incident security law enforcement bombing"],
  "a-.-X-i-l-l-b-e": cotEntity["Other incident security law enforcement bomb explosion"],
  "a-.-X-i-l-l-b-t": cotEntity["Other incident security law enforcementbomb threat"],
  "a-.-X-i-l-l-l": cotEntity["Other incident security law enforcement looting"],
  "a-.-X-i-l-l-p": cotEntity["Other incident security law enforcement poisoning"],
  "a-.-X-i-l-l-s": cotEntity["Other incident security law enforcement shooting"],
  "a-.-X-i-r": cotEntity["Other incident rescue"],
  "a-.-X-i-f": cotEntity["Other incident fire"],
  "a-.-X-i-f-w": cotEntity["Other incident fire wild"],
  "a-.-X-i-f-n": cotEntity["Other incident fire non residential"],
  "a-.-X-i-f-n-h": cotEntity["Other incident fire non residential special need"],
  "a-.-X-i-f-n-s": cotEntity["Other incident fire non residential school"],
  "a-.-X-i-f-r": cotEntity["Other incident fire residential"],
  "a-.-X-i-f-h": cotEntity["Other incident fire hot spot"],
  "a-.-X-i-f-o": cotEntity["Other incident fire origin"],
  "a-.-X-i-f-s": cotEntity["Other incident fire smoke"],
  "a-.-X-i-f-p": cotEntity["Other incident fire special needs"],
  "a-.-X-i-h": cotEntity["Other incident medical public health"],
  "a-.-X-i-e": cotEntity["Other incident pollution environmental"],
  "a-.-X-i-t": cotEntity["Other incident transportation "],
  "a-.-X-i-t-a": cotEntity["Other incident transportation air"],
  "a-.-X-i-t-a-a": cotEntity["Other incident transportation air accident"],
  "a-.-X-i-t-a-h": cotEntity["Other incident transportation air hijacking"],
  "a-.-X-i-t-m": cotEntity["Other incident transportation maritime"],
  "a-.-X-i-t-m-a": cotEntity["Other incident transportation maritime accident"],
  "a-.-X-i-t-m-h": cotEntity["Other incident transportation maritime hijacking"],
  "a-.-X-i-t-r": cotEntity["Other incident transportation rail"],
  "a-.-X-i-t-r-a": cotEntity["Other incident transportation rail accident"],
  "a-.-X-i-t-r-h": cotEntity["Other incident transportation rail hijacking"],
  "a-.-X-i-t-v": cotEntity["Other incident transportation vehicle"],
  "a-.-X-i-t-v-a": cotEntity["Other incident transportation vehicle accident"],
  "a-.-X-i-t-v-h": cotEntity["Other incident transportation vehicle hijacking"],
  "a-.-X-i-i": cotEntity["Other incident infrastructure"],
  "a-.-X-i-c": cotEntity["Other incident CBRNE"],
  "a-.-X-i-o": cotEntity["Other incident other"],
  "a-.-P": cotEntity["Space track"],
  "a-.-P-V": cotEntity["Crewed space vehicle"],
  "a-.-P-S": cotEntity["Satellite"],
  "a-.-P-T": cotEntity["Space station"],
  "a-.-F": cotEntity["SOF Unit"],
  "a-.-F-A": cotEntity["Aviation"],
  "a-.-F-A-F": cotEntity["Fixed wing"],
  "a-.-A-M-F-Q-A": cotEntity["Attack"],
  "a-.-F-G-R": cotEntity["Ranger"],
  "a-.-F-G-S": cotEntity["Special forces"],
  "a-.-F-N": cotEntity["Naval"],
  "a-.-F-N-S": cotEntity["SEAL"],
  "a-.-F-B": cotEntity["Support"],
  "a-.-A-M-F-Q-D": cotEntity["Airborne command post"],
  "a-.-A-M-F-Q-F": cotEntity["Fighter"],
  "t-x-v-m": cotEntity["Medevac"],
  "a-.-A-M-F-Q-P": cotEntity["Patrol"],
  "a-.-A-M-F-Q-H": cotEntity["Combat search &amp; rescue (CSAR)"],
  "a-.-A-M-F-Q-M": cotEntity["Special operations forces (SOF)"],
  "a-.-A-M-F-Q-K": cotEntity["Tanker"],
  "a-.-A-M-F-Q-T": cotEntity["Trainer"],
  "a-.-A-M-F-Q-U": cotEntity["Utility"],
  "a-.-A-W-B": cotEntity["Bomb"],
  "a-.-A-W-M-B": cotEntity["Ballistic missile"],
  "a-.-G-E-V-C-A": cotEntity["Automobile"],
  "a-.-G-E-V-C-J": cotEntity["Jeep type vehicle"],
  "a-.-G-E-V-C-M": cotEntity["Multi-passenger vehicle"],
  "a-.-G-E-V-C-O": cotEntity["Open-bed truck"],
  "a-.-G-E-V-C-T": cotEntity["Tractor trailer truck with box trailer"],
  "a-.-G-E-V-C-F": cotEntity["Tractor trailer truck with flatbed trailer"],
  "a-.-G-E-V-C-U": cotEntity["Utility vehicle"],
  "a-.-G-E-V-E-S": cotEntity["Armored assault"],
  "a-.-G-E-V-E-R": cotEntity["Armored engineer recon vehicle (AERV)"],
  "a-.-G-E-V-E-H": cotEntity["Backhoe"],
  "a-.-G-E-V-E-F": cotEntity["Ferry transporter"],
  "a-.-G-E-V-S-C": cotEntity["Crane loading device"],
  "a-.-G-E-V-U-A": cotEntity["Ambulance"],
  "a-.-G-E-V-U-T": cotEntity["Tow truck"],
  "a-.-G-E-V-C-J-M": cotEntity["Medium"],
  "a-.-S-C-A-L-S-T": cotEntity["Tank"],
  "a-.-S-C-L-L-L-A-S": cotEntity["Antisubmarine warfare mission package"],
  "a-.-S-C-L-L-L-M-I": cotEntity["Mine warfare mission package"],
  "a-.-S-C-L-L-L-S-U": cotEntity["Surface warfare (SUW) mission package"],
  "a-.-S-C-P-S-U-M": cotEntity["Anti-ship missile"],
  "a-.-S-C-P-S-U-G": cotEntity["Gun"],
  "a-.-S-C-P-S-U-T": cotEntity["Torpedo"],
  "a-.-A-M-F-Q-R-Z": cotEntity["Electronic surveillance measures"],
  "a-.-A-M-F-Q-R-X": cotEntity["Photographic"],
  "a-.-G-E-V-C-A-L": cotEntity["Compact"],
  "a-.-G-E-V-C-A-M": cotEntity["Midsize"],
  "a-.-G-E-V-C-A-H": cotEntity["Sedan"],
  "a-.-G-E-V-C-J-H": cotEntity["Large heavy"],
  "a-.-G-E-V-C-J-L": cotEntity["Small light"],
  "a-.-G-E-V-C-M-H": cotEntity["Large bus"],
  "a-.-G-E-V-C-M-M": cotEntity["Small bus"],
  "a-.-G-E-V-C-M-L": cotEntity["Van"],
  "a-.-G-E-V-C-O-H": cotEntity["Large open-bed truck"],
  "a-.-G-E-V-C-O-L": cotEntity["Pickup truck"],
  "a-.-G-E-V-C-O-M": cotEntity["Small open-bed truck"],
  "a-.-G-E-V-C-T-H": cotEntity["Large heavy box trailer"],
  "a-.-G-E-V-C-T-M": cotEntity["Medium box trailer"],
  "a-.-G-E-V-C-T-L": cotEntity["Small light box trailer"],
  "a-.-G-E-V-C-F-H": cotEntity["Large heavy flatbed trailer"],
  "a-.-G-E-V-C-F-M": cotEntity["Medium flatbed trailer"],
  "a-.-G-E-V-C-F-L": cotEntity["Small light flatbed trailer"],
  "a-.-G-E-V-C-U-H": cotEntity["Large box truck"],
  "a-.-G-E-V-C-U-M": cotEntity["Small box truck"],
  "a-.-G-E-V-C-U-L": cotEntity["Sport utility vehicle (SUV)"],
  "a-.-G-E-V-E-D-A": cotEntity["Armored dozer"],
  "a-.-G-E-V-U-A-A": cotEntity["Armored utility vehicle"],
  "a-.-G-E-V-U-S-H": cotEntity["Heavy semi"],
  "a-.-G-E-V-U-S-L": cotEntity["Light semi"],
  "a-.-G-E-V-U-S-M": cotEntity["Medium semi"],
  "a-.-G-E-V-U-T-H": cotEntity["Heavy tow truck"],
  "a-.-G-E-V-U-T-L": cotEntity["Light tow truck"],
  "a-.-G-U-C-D-S-C": cotEntity["Chaparral"],
  "a-.-G-U-C-V-R-C": cotEntity["C2"],
  "a-.-G-U-U-M-R-O": cotEntity["Meteorological"],
  "a-.-G-E-W-M-A-I-E": cotEntity["Int. range AD missile launcher TELAR"],
  "a-.-G-E-W-M-A-I-R": cotEntity["Int. range AD missile launcher TLAR"],
  "a-.-G-E-W-M-A-L-E": cotEntity["Long range AD missile launcher TELAR"],
  "a-.-G-E-W-M-A-L-R": cotEntity["Long range AD missile launcher TLAR"],
  "a-.-G-E-W-M-A-S-E": cotEntity["Short range AD missile launcher TELAR"],
  "a-.-G-E-W-M-A-S-R": cotEntity["Short range AD missile launcher TLAR"],
  "a-.-G-E-W-M-A-T-E": cotEntity["AD missile launcher theater TELAR"],
  "a-.-G-E-W-M-A-T-R": cotEntity["AD missile launcher theater TLAR"],
  "a-.-.*-9-1-1": cotEntity["Mayday message"],
  "b-m-p-s-p-loc": cotEntity["sensor point"],
  "b-m-p-s-p-op": cotEntity["observation point"],
  "b-m-g-o": cotEntity["grid"],
  "b-l": cotEntity["Alarm"],
  "b-l-c": cotEntity["Alarm/CBRNE"],
  "b-l-c-b": cotEntity["Alarm/CBRNE/BioChem"],
  "b-l-c-b-b": cotEntity["Alarm/CBRNE/BioChem/Biological"],
  "b-l-c-b-c": cotEntity["Alarm/CBRNE/BioChem/Chemical"],
  "b-l-c-e": cotEntity["Alarm/CBRNE/Explosive"],
  "b-l-c-e-d": cotEntity["Alarm/CBRNE/Explosive/Device"],
  "b-l-c-n": cotEntity["Alarm/CBRNE/NuclearRadiological"],
  "b-l-c-n-n": cotEntity["Alarm/CBRNE/NuclearRadiological/Nuclear"],
  "b-l-c-n-n-b": cotEntity["Alarm/CBRNE/NuclearRadiological/Nuclear/Bomb"],
  "b-l-c-n-n-sm": cotEntity["Alarm/CBRNE/NuclearRadiological/Nuclear/Special Nuclear Material"],
  "b-l-c-n-r": cotEntity["Alarm/CBRNE/NuclearRadiological/Radiological"],
  "b-l-c-n-r-dd": cotEntity["Alarm/CBRNE/Radiological/Dispersal Device (Dirty Bomb)"],
  "b-l-e": cotEntity["Alarm/Environmental"],
  "b-l-e-h": cotEntity["Alarm/Environmental/Hazmat"],
  "b-l-f": cotEntity["Alarm/Fire"],
  "b-l-f-a": cotEntity["Alarm/Fire/Audible"],
  "b-l-f-a-a": cotEntity["Alarm/Fire/Audible/Pump Activated"],
  "b-l-f-a-c": cotEntity["Alarm/Fire/Audible/Combustion"],
  "b-l-f-a-d": cotEntity["Alarm/Fire/Audible/Duct Detector"],
  "b-l-f-a-f": cotEntity["Alarm/Fire/Audible/Flame Detector"],
  "b-l-f-a-h": cotEntity["Alarm/Fire/Audible/Heat"],
  "b-l-f-a-p": cotEntity["Alarm/Fire/Audible/Pull Station"],
  "b-l-f-a-s": cotEntity["Alarm/Fire/Audible/Smoke"],
  "b-l-f-a-w": cotEntity["Alarm/Fire/Audible/Waterflow"],
  "b-l-g": cotEntity["Alarm/Geophysical"],
  "b-l-h": cotEntity["Alarm/Medical and Public Health"],
  "b-l-h-a": cotEntity["Alarm/Medical and Public Health/Audible"],
  "b-l-h-am": cotEntity["Alarm/Medical and Public Health/Ambulance"],
  "b-l-h-am-s": cotEntity["Alarm/Medical and Public Health/Ambulance/Silent"],
  "b-l-i": cotEntity["Alarm/Infrastructure"],
  "b-l-l": cotEntity["Alarm/Security"],
  "b-l-l-l": cotEntity["Alarm/Security/Law Enforcement"],
  "b-l-l-l-ad": cotEntity["Alarm/Security/Law Enforcement/Armed and Dangerous"],
  "b-l-l-l-an": cotEntity["Alarm/Security/Law Enforcement/Animal"],
  "b-l-l-l-an-or": cotEntity["Alarm/Security/Law Enforcement/Animal/On Roadway"],
  "b-l-l-l-as": cotEntity["Alarm/Security/Law Enforcement/Assualt"],
  "b-l-l-l-av": cotEntity["Alarm/Security/Law Enforcement/Abandoned Vehicle"],
  "b-l-l-l-ba": cotEntity["Alarm/Security/Law Enforcement/Battery"],
  "b-l-l-l-bt": cotEntity["Alarm/Security/Law Enforcement/Bomb Threat"],
  "b-l-l-l-bur": cotEntity["Alarm/Security/Law Enforcement/Burglary"],
  "b-l-l-l-bur-a": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible"],
  "b-l-l-l-bur-a-d": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Day/Night Zone"],
  "b-l-l-l-bur-a-e": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Entry/Exit"],
  "b-l-l-l-bur-a-i": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Interior"],
  "b-l-l-l-bur-a-o": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Outdoor"],
  "b-l-l-l-bur-a-p": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Perimeter"],
  "b-l-l-l-bur-a-t": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/24 Hour Zone"],
  "b-l-l-l-bur-a-x": cotEntity["Alarm/Security/Law Enforcement/Burglary/Audible/Exit Error"],
  "b-l-l-l-bur-s": cotEntity["Alarm/Security/Law Enforcement/Burglary/Silent"],
  "b-l-l-l-bur-s-c": cotEntity["Alarm/Security/Law Enforcement/Burglary/Silent/Recent Close"],
  "b-l-l-l-c": cotEntity["Alarm/Security/Law Enforcement/Crash"],
  "b-l-l-l-c-a": cotEntity["Alarm/Security/Law Enforcement/Crash/Aircraft"],
  "b-l-l-l-c-wf": cotEntity["Alarm/Security/Law Enforcement/Crash/With Fatalities"],
  "b-l-l-l-c-wi": cotEntity["Alarm/Security/Law Enforcement/Crash/With injuries"],
  "b-l-l-l-c-wr": cotEntity["Alarm/Security/Law Enforcement/Crash/With Roadblock"],
  "b-l-l-l-c-pc": cotEntity["Alarm/Security/Law Enforcement/Crash/Patrol Car"],
  "b-l-l-l-ca": cotEntity["Alarm/Security/Law Enforcement/Child Abuse"],
  "b-l-l-l-cd": cotEntity["Alarm/Security/Law Enforcement/Civil Disturbance or Disorder"],
  "b-l-l-l-cr": cotEntity["Alarm/Security/Law Enforcement/Callbox Request"],
  "b-l-l-l-dc": cotEntity["Alarm/Security/Law Enforcement/Drug or Contraband"],
  "b-l-l-l-dov": cotEntity["Alarm/Security/Law Enforcement/Domestic Violence"],
  "b-l-l-l-dp": cotEntity["Alarm/Security/Law Enforcement/Dead Person"],
  "b-l-l-l-drp": cotEntity["Alarm/Security/Law Enforcement/Drunk Pedestrian"],
  "b-l-l-l-dui-j": cotEntity["Alarm/Security/Law Enforcement/DUI/Juvenile"],
  "b-l-l-l-dv": cotEntity["Alarm/Security/Law Enforcement/Disabled Vehicle"],
  "b-l-l-l-ep": cotEntity["Alarm/Security/Law Enforcement/Escaped Prisoner"],
  "b-l-l-l-hr": cotEntity["Alarm/Security/Law Enforcement/Hit and Run"],
  "b-l-l-l-hr-wi": cotEntity["Alarm/Security/Law Enforcement/Hit and Run/With Injuries"],
  "b-l-l-l-hr-wr": cotEntity["Alarm/Security/Law Enforcement/Hit and Run/With Roadblock"],
  "b-l-l-l-hup": cotEntity["Alarm/Security/Law Enforcement/Hold Up"],
  "b-l-l-l-hup-a": cotEntity["Alarm/Security/Law Enforcement/Hold Up/Audible"],
  "b-l-l-l-hup-s": cotEntity["Alarm/Security/Law Enforcement/Hold Up/Silent"],
  "b-l-l-l-ii": cotEntity["Alarm/Security/Law Enforcement/Information or Intelligence - calls to take witness info"],
  "b-l-l-l-io": cotEntity["Alarm/Security/Law Enforcement/Impersonating an Officer"],
  "b-l-l-l-jo": cotEntity["Alarm/Security/Law Enforcement/Juvenile Offense"],
  "b-l-l-l-k": cotEntity["Alarm/Security/Law Enforcement/Kidnapping"],
  "b-l-l-l-l": cotEntity["Alarm/Security/Law Enforcement/Larceny"],
  "b-l-l-l-m": cotEntity["Alarm/Security/Law Enforcement/Murder"],
  "b-l-l-l-mi": cotEntity["Alarm/Security/Law Enforcement/Mentally Ill Person"],
  "b-l-l-l-mm": cotEntity["Alarm/Security/Law Enforcement/Malacious Mischief"],
  "b-l-l-l-mp": cotEntity["Alarm/Security/Law Enforcement/Missing Person"],
  "b-l-l-l-od": cotEntity["Alarm/Security/Law Enforcement/Officer Down"],
  "b-l-l-l-ph": cotEntity["Alarm/Security/Law Enforcement/Pedestrian or Hitchhiker"],
  "b-l-l-l-r": cotEntity["Alarm/Security/Law Enforcement/Robbery"],
  "b-l-l-l-r-sa": cotEntity["Alarm/Security/Law Enforcement/Robbery/Strongarm"],
  "b-l-l-l-rd": cotEntity["Alarm/Security/Law Enforcement/Reckless Driving"],
  "b-l-l-l-rt": cotEntity["Alarm/Security/Law Enforcement/Rock Throwing"],
  "b-l-l-l-s": cotEntity["Alarm/Security/Law Enforcement/Shooting"],
  "b-l-l-l-sc": cotEntity["Alarm/Security/Law Enforcement/Suspicious Circumstances"],
  "b-l-l-l-sd": cotEntity["Alarm/Security/Law Enforcement/Special Detail"],
  "b-l-l-l-sg": cotEntity["Alarm/Security/Law Enforcement/Smuggling"],
  "b-l-l-l-si": cotEntity["Alarm/Security/Law Enforcement/Sick or Injured Person"],
  "b-l-l-l-so": cotEntity["Alarm/Security/Law Enforcement/Sex Offense"],
  "b-l-l-l-sp": cotEntity["Alarm/Security/Law Enforcement/Suspicious Person"],
  "b-l-l-l-su": cotEntity["Alarm/Security/Law Enforcement/Suicide"],
  "b-l-l-l-sv": cotEntity["Alarm/Security/Law Enforcement/Suspicious Vehcle"],
  "b-l-l-l-te": cotEntity["Alarm/Security/Law Enforcement/Toll Evasion"],
  "b-l-l-l-vt": cotEntity["Alarm/Security/Law Enforcement/Lost or Stolen Vehicle Tag"],
  "b-l-m": cotEntity["Alarm/Meteorological"],
  "b-l-o": cotEntity["Alarm/Other"],
  "b-l-o-can": cotEntity["Alarm/Other/Cancel"],
  "b-l-o-clo": cotEntity["Alarm/Other/Close"],
  "b-l-o-clo-s": cotEntity["Alarm/Other/Close/Silent"],
  "b-l-o-clo-s-sm": cotEntity["Alarm/Other/Close/Silent/Stay Mode"],
  "b-l-o-far": cotEntity["Alarm/Other/Forced Arming"],
  "b-l-o-far-s": cotEntity["Alarm/Other/Forced Arming/Silent"],
  "b-l-o-far-s-pa": cotEntity["Alarm/Other/Forced Arming/Silent/Partial Arm"],
  "b-l-o-ftt": cotEntity["Alarm/Other/Failure to Test"],
  "b-l-o-ftt-s": cotEntity["Alarm/Other/Failure to Test/Silent"],
  "b-l-o-ftt-s-pn": cotEntity["Alarm/Other/Failure to Test/Silent/Point not Tested"],
  "b-l-o-log": cotEntity["Alarm/Other/Log"],
  "b-l-o-pan": cotEntity["Alarm/Other/Panic"],
  "b-l-o-res": cotEntity["Alarm/Other/Reset"],
  "b-l-o-res-s": cotEntity["Alarm/Other/Reset/Silent"],
  "b-l-o-res-s-er": cotEntity["Alarm/Other/Reset/Silent/Exp Mod Reset"],
  "b-l-o-spc": cotEntity["Alarm/Other/Special"],
  "b-l-o-spc-a": cotEntity["Alarm/Other/Special/Audible"],
  "b-l-o-spc-a-a": cotEntity["Alarm/Other/Special/Audible/General Alarm"],
  "b-l-o-spc-a-e": cotEntity["Alarm/Other/Special/Audible/Personal Emergency"],
  "b-l-o-spc-a-f": cotEntity["Alarm/Other/Special/Audible/Air Flow Loss"],
  "b-l-o-spc-a-g": cotEntity["Alarm/Other/Special/Audible/Gas Detected"],
  "b-l-o-spc-a-l": cotEntity["Alarm/Other/Special/Audible/Low Gas Level"],
  "b-l-o-spc-a-w": cotEntity["Alarm/Other/Special/Audible/Water Leakage"],
  "b-l-o-spc-s": cotEntity["Alarm/Other/Special/Silent"],
  "b-l-o-spc-s-f": cotEntity["Alarm/Other/Special/Silent/Fail to Report"],
  "b-l-o-spc-s-li": cotEntity["Alarm/Other/Special/Silent/Listen in to Follow"],
  "b-l-o-sps": cotEntity["Alarm/Other/Supress"],
  "b-l-o-sps-a": cotEntity["Alarm/Other/Supress/Audible"],
  "b-l-o-sps-a-g": cotEntity["Alarm/Other/Supress/Audible/Gate Valve Tamper"],
  "b-l-o-sps-s": cotEntity["Alarm/Other/Supress/Silent"],
  "b-l-o-sps-s-ar": cotEntity["Alarm/Other/Supress/Silent/Alarm Relay Disabled"],
  "b-l-o-sps-s-b1": cotEntity["Alarm/Other/Supress/Silent/Bell 1 Disabled"],
  "b-l-o-sps-s-b2": cotEntity["Alarm/Other/Supress/Silent/Bell 2 Disabled"],
  "b-l-o-sps-s-dd": cotEntity["Alarm/Other/Supress/Silent/Dialer Disabled"],
  "b-l-o-sps-s-rr": cotEntity["Alarm/Other/Supress/Silent/Reversing Relay Disabled"],
  "b-l-o-sps-s-rx": cotEntity["Alarm/Other/Supress/Silent/Radio Transmitter Disabled"],
  "b-l-o-sps-s-sr": cotEntity["Alarm/Other/Supress/Silent/Sounder relay Disabled"],
  "b-l-o-sps-s-tr": cotEntity["Alarm/Other/Supress/Silent/Trouble Relay Disabled"],
  "b-l-o-tam": cotEntity["Alarm/Other/Tamper"],
  "b-l-o-tam-a": cotEntity["Alarm/Other/Tamper/Audible"],
  "b-l-o-tam-s": cotEntity["Alarm/Other/Tamper/Silent"],
  "b-l-o-tam-s-e": cotEntity["Alarm/Other/Tamper/Silent/Expansion Module"],
  "b-l-o-tam-s-p": cotEntity["Alarm/Other/Tamper/Silent/Panel Program Change"],
  "b-l-o-tam-s-s": cotEntity["Alarm/Other/Tamper/Silent/Sensor"],
  "b-l-o-tam-s-v": cotEntity["Alarm/Other/Tamper/Silent/Verify"],
  "b-l-o-tbl": cotEntity["Alarm/Other/Trouble"],
  "b-l-o-tbl-a": cotEntity["Alarm/Other/Trouble/Audible"],
  "b-l-o-tbl-a-b": cotEntity["Alarm/Other/Trouble/Audible/Foil Break"],
  "b-l-o-tbl-a-c": cotEntity["Alarm/Other/Trouble/Audible/Low CO2"],
  "b-l-o-tbl-a-d": cotEntity["Alarm/Other/Trouble/Audible/Day Trouble"],
  "b-l-o-tbl-a-ee": cotEntity["Alarm/Other/Trouble/Audible/Exit error"],
  "b-l-o-tbl-a-l": cotEntity["Alarm/Other/Trouble/Audible/Low Water Level"],
  "b-l-o-tbl-a-p": cotEntity["Alarm/Other/Trouble/Audible/Low  Water Pressure"],
  "b-l-o-tbl-a-u": cotEntity["Alarm/Other/Trouble/Audible/Pump Failure"],
  "b-l-o-tbl-s": cotEntity["Alarm/Other/Trouble/Silent"],
  "b-l-o-tbl-s-a": cotEntity["Alarm/Other/Trouble/Silent/Sensor"],
  "b-l-o-tbl-s-ar": cotEntity["Alarm/Other/Trouble/Silent/Alarm Relay"],
  "b-l-o-tbl-s-b": cotEntity["Alarm/Other/Trouble/Silent/Low System Battery"],
  "b-l-o-tbl-s-b1": cotEntity["Alarm/Other/Trouble/Silent/Bell 1"],
  "b-l-o-tbl-s-b2": cotEntity["Alarm/Other/Trouble/Silent/Bell 2"],
  "b-l-o-tbl-s-bt": cotEntity["Alarm/Other/Trouble/Silent/Battery Test Fail"],
  "b-l-o-tbl-s-c": cotEntity["Alarm/Other/Trouble/Silent/Polling Loop Close"],
  "b-l-o-tbl-s-cf": cotEntity["Alarm/Other/Trouble/Silent/Communication Fail"],
  "b-l-o-tbl-s-dc": cotEntity["Alarm/Other/Trouble/Silent/Exp Mod DC Loss"],
  "b-l-o-tbl-s-dh": cotEntity["Alarm/Other/Trouble/Silent/Detector Hi Sens"],
  "b-l-o-tbl-s-dl": cotEntity["Alarm/Other/Trouble/Silent/Detector Low Sens"],
  "b-l-o-tbl-s-e": cotEntity["Alarm/Other/Trouble/Silent/Expansion Mod Fail"],
  "b-l-o-tbl-s-e50": cotEntity["Alarm/Other/Trouble/Silent/Event Log 50% Full"],
  "b-l-o-tbl-s-e90": cotEntity["Alarm/Other/Trouble/Silent/Event Log 90% Full"],
  "b-l-o-tbl-s-em": cotEntity["Alarm/Other/Trouble/Silent/Expansion Module Fail"],
  "b-l-o-tbl-s-eo": cotEntity["Alarm/Other/Trouble/Silent/Event Log Overflow"],
  "b-l-o-tbl-s-ft": cotEntity["Alarm/Other/Trouble/Silent/Fire Trouble"],
  "b-l-o-tbl-s-gf": cotEntity["Alarm/Other/Trouble/Silent/Ground Fault"],
  "b-l-o-tbl-s-lb": cotEntity["Alarm/Other/Trouble/Silent/Exp Mod Low Battery"],
  "b-l-o-tbl-s-lo": cotEntity["Alarm/Other/Trouble/Silent/Protection Loop Open"],
  "b-l-o-tbl-s-lp": cotEntity["Alarm/Other/Trouble/Silent/Lost Polling"],
  "b-l-o-tbl-s-lr": cotEntity["Alarm/Other/Trouble/Silent/Long Range Radio"],
  "b-l-o-tbl-s-ls": cotEntity["Alarm/Other/Trouble/Silent/Protection Loop Short"],
  "b-l-o-tbl-s-ms": cotEntity["Alarm/Other/Trouble/Silent/RPM Supervision"],
  "b-l-o-tbl-s-n": cotEntity["Alarm/Other/Trouble/Silent/Near Alarm"],
  "b-l-o-tbl-s-o": cotEntity["Alarm/Other/Trouble/Silent/Polling Loop Open"],
  "b-l-o-tbl-s-p": cotEntity["Alarm/Other/Trouble/Silent/AC Power Lost"],
  "b-l-o-tbl-s-pf": cotEntity["Alarm/Other/Trouble/Silent/Printer Failure"],
  "b-l-o-tbl-s-pl": cotEntity["Alarm/Other/Trouble/Silent/Protection Loop"],
  "b-l-o-tbl-s-pp": cotEntity["Alarm/Other/Trouble/Silent/Printer Paper Out"],
  "b-l-o-tbl-s-ps": cotEntity["Alarm/Other/Trouble/Silent/Polling Loop Short"],
  "b-l-o-tbl-s-ra": cotEntity["Alarm/Other/Trouble/Silent/Radio Antenna Vswr"],
  "b-l-o-tbl-s-rf": cotEntity["Alarm/Other/Trouble/Silent/Repeater Failure"],
  "b-l-o-tbl-s-rfb": cotEntity["Alarm/Other/Trouble/Silent/RF Low Battery"],
  "b-l-o-tbl-s-rr": cotEntity["Alarm/Other/Trouble/Silent/Reversing Relay"],
  "b-l-o-tbl-s-rs": cotEntity["Alarm/Other/Trouble/Silent/RF Supervision"],
  "b-l-o-tbl-s-sh": cotEntity["Alarm/Other/Trouble/Silent/Smoke Det Hi Sens"],
  "b-l-o-tbl-s-sl": cotEntity["Alarm/Other/Trouble/Silent/Smoke Det Low Sens"],
  "b-l-o-tbl-s-sp": cotEntity["Alarm/Other/Trouble/Silent/System Peripheral"],
  "b-l-o-tbl-s-sr": cotEntity["Alarm/Other/Trouble/Silent/Sounder/Relay"],
  "b-l-o-tbl-s-ss": cotEntity["Alarm/Other/Trouble/Silent/System Shutdown"],
  "b-l-o-tbl-s-st": cotEntity["Alarm/Other/Trouble/Silent/Self Test Failure"],
  "b-l-o-tbl-s-t1": cotEntity["Alarm/Other/Trouble/Silent/Telco Line 1"],
  "b-l-o-tbl-s-t2": cotEntity["Alarm/Other/Trouble/Silent/Telco Line 2"],
  "b-l-o-tbl-s-ti": cotEntity["Alarm/Other/Trouble/Silent/Time/Date Inaccurate"],
  "b-l-o-tbl-s-tr": cotEntity["Alarm/Other/Trouble/Silent/Trouble Relay"],
  "b-l-o-tbl-s-x": cotEntity["Alarm/Other/Trouble/Silent/RAM Checksum Bad"],
  "b-l-o-tbl-s-y": cotEntity["Alarm/Other/Trouble/Silent/ROM Checksum Bad"],
  "b-l-o-tem": cotEntity["Alarm/Other/Temperature"],
  "b-l-o-tem-a": cotEntity["Alarm/Other/Temperature/Audible"],
  "b-l-o-tem-a-h": cotEntity["Alarm/Other/Temperature/Audible/High Temperature"],
  "b-l-o-tem-a-l": cotEntity["Alarm/Other/Temperature/Audible/Low Temperature"],
  "b-l-o-tem-a-lh": cotEntity["Alarm/Other/Temperature/Audible/Loss of Heat"],
  "b-l-o-tem-a-r": cotEntity["Alarm/Other/Temperature/Audible/Refrigeration"],
  "b-l-o-tst": cotEntity["Alarm/Other/Test"],
  "b-l-o-tst-s": cotEntity["Alarm/Other/Test/SIlent"],
  "b-l-o-tst-s-fa": cotEntity["Alarm/Other/Test/SIlent/Fire Alarm"],
  "b-l-o-tst-s-m": cotEntity["Alarm/Other/Test/SIlent/Manual"],
  "b-l-o-tst-s-pt": cotEntity["Alarm/Other/Test/SIlent/Point Tested OK"],
  "b-l-o-tst-s-st": cotEntity["Alarm/Other/Test/SIlent/System Remains in Trouble"],
  "b-l-o-tst-s-wm": cotEntity["Alarm/Other/Test/SIlent/Walk Test Mode Entered"],
  "b-l-r": cotEntity["Alarm/Rescue"],
  "b-l-s": cotEntity["Alarm/Safety"],
  "b-l-t": cotEntity["Alarm/Transportation"],
  "b-l-t-v": cotEntity["Alarm/Transportation/Vehicle"],
  "b-l-t-v-a": cotEntity["Alarm/Transportation/Vehicle/Accident"],
  "b-l-t-v-a-c": cotEntity["Alarm/Transportation/Vehicle/Accident/Collision"],
  "b-l-t-v-a-c-f": cotEntity["Alarm/Transportation/Vehicle/Accident/Collision/Fixed Object"],
  "b-l-t-v-a-c-n": cotEntity["Alarm/Transportation/Vehicle/Accident/Collision/Non-Fixed Object"],
  "b-l-t-v-a-e": cotEntity["Alarm/Transportation/Vehicle/Accident/Equipment/Cargo Loss/Shift"],
  "b-l-t-v-a-f": cotEntity["Alarm/Transportation/Vehicle/Accident/Fire_Explosion"],
  "b-l-t-v-a-i": cotEntity["Alarm/Transportation/Vehicle/Accident/Immersion"],
  "b-l-t-v-a-j": cotEntity["Alarm/Transportation/Vehicle/Accident/Jacknife"],
  "b-l-t-v-a-o": cotEntity["Alarm/Transportation/Vehicle/Accident/Object Thrown/Fallen"],
  "b-l-t-v-a-or": cotEntity["Alarm/Transportation/Vehicle/Accident/Overturn_Rollover"],
  "b-l-t-v-a-p": cotEntity["Alarm/Transportation/Vehicle/Accident/Person Fell or Jumped"],
  "b-l-t-v-o": cotEntity["Alarm/Transportation/Vehicle/Other (Non Collision)"],
  "t-a-s": cotEntity["SEAD"],
  "t-k": cotEntity["Strike"],
  "t-k-d": cotEntity["Destroy"],
  "t-k-i": cotEntity["Investigate"],
  "t-k-t": cotEntity["Target"],
  "t-m": cotEntity["Mensurate"],
  "t-u": cotEntity["Tasking Update"],
  "t-u-q": cotEntity["Tasking Status Query"],
  "t-u-z": cotEntity["Tasking Cancel"],
  "t-x": cotEntity["Tasking (Experimental)"],
  "t-x-i": cotEntity["Tasking Data Retrieval"],
  "t-x-i-l": cotEntity["Link Dereference"],
  "t-x-a-s": cotEntity["App control- Sync (with peer)"],
  "t-x-a-s-c": cotEntity["App control- Sync (subscribe)"],
  "t-x-a-f": cotEntity["Filter"],
  "t-x-a-o": cotEntity["Open"],
  "y": cotEntity["Reply"],
  "y-a": cotEntity["Ack"],
  "y-a-r": cotEntity["Rcvd"],
  "y-a-w": cotEntity["Wilco"],
  "y-c": cotEntity["Tasking Complete"],
  "y-c-f": cotEntity["Fail"],
  "y-c-f-a": cotEntity["Fail= No Assets"],
  "y-c-f-b": cotEntity["Fail= Bad Reqest (CANTPRO)"],
  "y-c-f-d": cotEntity["Fail= Denied"],
  "y-c-f-i": cotEntity["Fail= Insufficient Info"],
  "y-c-f-r": cotEntity["Fail= Rejected"],
  "y-c-f-r-c": cotEntity["Fail= C2 element"],
  "y-c-f-r-p": cotEntity["Fail= Platform (CANTCO)"],
  "y-c-f-s": cotEntity["Fail= Stale"],
  "y-c-f-x": cotEntity["Fail= Cancelled"],
  "y-c-s": cotEntity["Complete= Success"],
  "y-s": cotEntity["Status= Status"],
  "y-s-c": cotEntity["Status= Canceling"],
  "y-s-e": cotEntity["Status= Executing"],
  "y-s-e-a": cotEntity["Status= Approved"],
  "y-s-e-d": cotEntity["Status= Disseminating"],
  "y-s-e-d-c": cotEntity["Status= Disseminated"],
  "y-s-i": cotEntity["Status= Imagery Available"],
  "y-s-m": cotEntity["Status= MISREP available"],
  "y-s-p": cotEntity["Status= Planning"],
  "y-s-r": cotEntity["Status= Reviewing"],
  "b-w": cotEntity["METOC"],
  "b-w-A": cotEntity["ATMOSPHERIC"],
  "b-w-A-t": cotEntity["Temperature"],
  "b-w-A-P": cotEntity["PRESSURE SYSTEMS"],
  "b-w-A-P-L": cotEntity["LOW PRESSURE CENTER"],
  "b-w-A-P-H": cotEntity["HIGH PRESSURE CENTER"],
  "b-w-A-P-F": cotEntity["FRONTAL SYSTEMS"],
  "b-w-A-P-F-C": cotEntity["COLD FRONT"],
  "b-w-A-P-F-C-U": cotEntity["UPPER COLD FRONT"],
  "b-w-A-P-F-W": cotEntity["WARM FRONT"],
  "b-w-A-P-F-W-U": cotEntity["UPPER WARM FRONT"],
  "b-w-A-P-F-O": cotEntity["OCCLUDED FRONT"],
  "b-w-A-P-F-S": cotEntity["STATIONARY FRONT"],
  "b-w-A-P-X": cotEntity["LINES"],
  "b-w-A-P-X-T": cotEntity["TROUGH LINE"],
  "b-w-A-P-X-R": cotEntity["RIDGE LINE"],
  "b-w-A-P-X-S": cotEntity["SQUALL LINE"],
  "b-w-A-T": cotEntity["TURBULENCE"],
  "b-w-A-T-L": cotEntity["LIGHT TURBULENCE"],
  "b-w-A-T-M": cotEntity["MODERATE TURBULENCE"],
  "b-w-A-T-S": cotEntity["SEVERE TURBULENCE"],
  "b-w-A-T-E": cotEntity["EXTREME TURBULENCE"],
  "b-w-A-I": cotEntity["ICING"],
  "b-w-A-I-C": cotEntity["CLEAR ICING"],
  "b-w-A-I-C-L": cotEntity["LIGHT CLEAR ICING"],
  "b-w-A-I-C-M": cotEntity["MODERATE CLEAR ICING"],
  "b-w-A-I-C-S": cotEntity["SEVERE CLEAR ICING"],
  "b-w-A-I-R": cotEntity["RIME ICING"],
  "b-w-A-I-R-L": cotEntity["LIGHT RIME ICING"],
  "b-w-A-I-R-M": cotEntity["MODERATE RIME ICING"],
  "b-w-A-I-R-S": cotEntity["SEVERE RIME ICING"],
  "b-w-A-I-M": cotEntity["MIXED ICING"],
  "b-w-A-I-M-L": cotEntity["LIGHT MIXED ICING"],
  "b-w-A-I-M-M": cotEntity["MODERATE MIXED ICING"],
  "b-w-A-I-M-S": cotEntity["SEVERE MIXED ICING"],
  "b-w-A-W": cotEntity["WIND BARB"],
  "b-w-A-W-J": cotEntity["JET STREAM"],
  "b-w-A-F": cotEntity["FLIGHT RULES"],
  "b-w-A-F-I": cotEntity["INSTRUMENT CEILING"],
  "b-w-A-F-V": cotEntity["VISUAL CEILING"],
  "b-w-A-C": cotEntity["COVERAGE SYMBOLS"],
  "b-w-A-C-t": cotEntity["Cloud tops"],
  "b-w-A-C-b": cotEntity["Cloud base"],
  "b-w-A-C-c": cotEntity["Cloud ceiling"],
  "b-w-A-C-a": cotEntity["Total Cloud Coverage"],
  "b-w-A-C-C": cotEntity["CLEAR SKY (SKC)"],
  "b-w-A-C-S": cotEntity["SCATTERED SKY (SCT)"],
  "b-w-A-C-B": cotEntity["BROKEN SKY (BKN)"],
  "b-w-A-C-W": cotEntity["OVERCAST WITH BREAKS"],
  "b-w-A-C-O": cotEntity["OVERCAST (OVC)"],
  "b-w-A-C-P": cotEntity["SKY OBSCURED OR PARTIALLY OBSCURED"],
  "b-w-A-R": cotEntity["PRECIPITATION"],
  "b-w-A-R-R": cotEntity["RAIN (RA)"],
  "b-w-A-R-R-S": cotEntity["RAIN SHOWER"],
  "b-w-A-R-R-F": cotEntity["FREEZING RAIN (FZRA)"],
  "b-w-A-R-R-D": cotEntity["DRIZZLE (DZ)"],
  "b-w-A-R-R-D-F": cotEntity["FREEZING DRIZZLE (FZDZ)"],
  "b-w-A-R-S": cotEntity["SNOW(SN)"],
  "b-w-A-R-S-S": cotEntity["SNOW SHOWERS"],
  "b-w-A-R-S-G": cotEntity["SNOW GRAINS (SG)"],
  "b-w-A-R-H": cotEntity["HAIL"],
  "b-w-A-R-I": cotEntity["ICE PELLETS (PE)"],
  "b-w-A-R-C": cotEntity["ICE CRYSTALS (IC)"],
  "b-w-A-S": cotEntity["STORMS"],
  "b-w-A-S-T": cotEntity["THUNDERSTORMS (TS)"],
  "b-w-A-S-T-R": cotEntity["THUNDERSTORM (TS) WITH RAIN (RA) "],
  "b-w-A-S-T-F": cotEntity["FUNNEL CLOUD (FC)/TORNADO/WATERSPOUT"],
  "b-w-A-S-T-L": cotEntity["LIGHTNING (LTG)"],
  "b-w-A-S-S": cotEntity["STORM SYSTEMS"],
  "b-w-A-S-S-T": cotEntity["TROPICAL STORM"],
  "b-w-A-S-S-H": cotEntity["HURRICANE"],
  "b-w-A-O": cotEntity["OBSTRUCTIONS TO VISIBILITY"],
  "b-w-A-O-S": cotEntity["BLOWING SNOW (BLSN)"],
  "b-w-A-O-F": cotEntity["FOG (FG)"],
  "b-w-A-O-F-F": cotEntity["FREEZING FOG (FZFG)"],
  "b-w-A-O-T": cotEntity["DUST/SAND STORM"],
  "b-w-A-O-D": cotEntity["DUST DEVIL"],
  "b-w-A-O-K": cotEntity["SMOKE (FU)"],
  "b-w-A-O-H": cotEntity["HAZE (HZ)"],
  "b-w-A-O-B": cotEntity["BLOWING DUST OR SAND"],
  "b-w-O": cotEntity["OCEANIC"],
  "b-w-S": cotEntity["SPACE"],
  "b-r-.-h-c": cotEntity["HEALTH/CASUALTY"],
  "b-r-.-O": cotEntity["MILITARY OPERATIONS OTHER THAN WAR (MOOTW)"],
  "b-r-.-O-V": cotEntity["VIOLENT ACTIVITIES (DEATH CAUSING)"],
  "b-r-.-O-V-A": cotEntity["ARSON/FIRE"],
  "b-r-.-O-V-M": cotEntity["ASSASSINATION/MURDER/EXECUTION"],
  "b-r-.-O-V-B": cotEntity["BOMB/BOMBING"],
  "b-r-.-O-V-Y": cotEntity["BOOBY TRAP"],
  "b-r-.-O-V-D": cotEntity["DRIVE BY SHOOTING"],
  "b-r-.-O-V-S": cotEntity["SNIPING"],
  "b-r-.-O-V-P": cotEntity["POISONING"],
  "b-r-.-O-L": cotEntity["LOCATIONS"],
  "b-r-.-O-L-B": cotEntity["BLACK LIST LOCATION"],
  "b-r-.-O-L-G": cotEntity["GRAY LIST LOCATION"],
  "b-r-.-O-L-W": cotEntity["WHITE LIST LOCATION"],
  "b-r-.-O-O": cotEntity["OPERATIONS"],
  "b-r-.-O-O-P": cotEntity["PATROLLING"],
  "b-r-.-O-O-R": cotEntity["RECRUITMENT"],
  "b-r-.-O-O-R-W": cotEntity["RECRUITMENT (WILLING)"],
  "b-r-.-O-O-R-C": cotEntity["RECRUITMENT (COERCED/IMPRESSED)"],
  "b-r-.-O-O-D": cotEntity["DEMONSTRATION"],
  "b-r-.-O-O-M": cotEntity["MINE LAYING"],
  "b-r-.-O-O-Y": cotEntity["PSYCHOLOGICAL OPERATIONS (PSYOP)"],
  "b-r-.-O-O-Y-T": cotEntity["PSYOP (TV AND RADIO PROPAGANDA)"],
  "b-r-.-O-O-Y-W": cotEntity["PSYOP (WRITTEN PROPAGANA)"],
  "b-r-.-O-O-Y-H": cotEntity["HOUSE TO HOUSE PROPAGANDA"],
  "b-r-.-O-O-F": cotEntity["FORAGING/SEARCHING"],
  "b-r-.-O-O-S": cotEntity["SPY"],
  "b-r-.-O-O-O": cotEntity["FOOD DISTRIBUTION"],
  "b-r-.-O-O-E": cotEntity["EXTORTION"],
  "b-r-.-O-O-H": cotEntity["HIJACKING"],
  "b-r-.-O-O-H-T": cotEntity["HIJACKING (VEHICLE)"],
  "b-r-.-O-O-H-A": cotEntity["HIJACKING (AIRPLANE)"],
  "b-r-.-O-O-H-V": cotEntity["HIJACKING (BOAT)"],
  "b-r-.-O-O-K": cotEntity["KIDNAPPING"],
  "b-r-.-O-O-A": cotEntity["ARREST"],
  "b-r-.-O-O-U": cotEntity["DRUG OPERATION"],
  "b-r-.-O-I": cotEntity["ITEMS"],
  "b-r-.-O-I-R": cotEntity["REFUGEES"],
  "b-r-.-O-I-S": cotEntity["SAFE HOUSE"],
  "b-r-.-O-I-G": cotEntity["GRAFITTI"],
  "b-r-.-O-I-V": cotEntity["VANDALISM/RAPE/LOOT/RANSACK/PLUNDER/SACK"],
  "b-r-.-O-I-I": cotEntity["KNOWN INSURGENT VEHICLE"],
  "b-r-.-O-I-D": cotEntity["DRUG VEHICLE"],
  "b-r-.-O-I-F": cotEntity["INTERNAL SECURITY FORCE"],
  "b-x.*": cotEntity["NON-COT OBJECT"]
}
